### ISSUE TITLE
how can i build for xcode or android studio,not only the commond, i want to open the project form the IDE.thanks

### ISSUE THREAD

**Issue by jaccen** [google/filament#1014]
how can i build for xcode or android studio,not only the commond, i want to open the project form the IDE.thanks

**Comment by romainguy** [comment]
Since we use `CMake` you can use a CMake generator to create an XCode project. We use the CLion IDE to open the CMake project directly. Android Studio cannot open the whole project (since it's not Android specific), but you can open any of the projects in the `android/` directory from Android Studio.

**Comment by jaccen** [comment]
when i open android/ anyfile from android studio,but can not make an app?  is there any configure?
