### ISSUE TITLE
filamat failed to create a valid material Package on iOS

### ISSUE THREAD

**Issue by luanbach** [google/filament#1101]
I've been trying to replicate the sample_full_pbr example on iOS. I can't seem to get it to work, the call to an object MaterialBuilder::build() created a Package that failed the Material.build() step.

The error is 
```
utils::PostconditionPanic
in filament::Material *filament::Material::Builder::build(filament::Engine &):79
in file filament/src/Material.cpp
reason: could not parse the material package
```

I've attached an example xcode project based on the hello-pbr-Metal sample. Please run the Metal rendering path.

[modified hello-pbr](https://drive.google.com/file/d/1jFoDka7L6UH4VcxgTOhgrA6gd6p3Fo-q/view?usp=sharing)

I don't know what I'm getting wrong.

**Comment by bejado** [comment]
I see you copied over `shaders.apple.S` into the sample's generated/ folder and added

```
#include "shaders.apple.S"
```

to Resources.S. This fixes linker errors, but is incorrect. The correct fix is to add the `-lshaders` flag to the "Other Linker Flags" of the Xcode project to link against the libshaders.a library. I'll make this clearer in our documentation.

You'll also want to add
```
builder.targetApi(MaterialBuilder::TargetApi::METAL);
builder.platform(MaterialBuilder::Platform::MOBILE);
```

before building in order to build shaders for Metal on iOS.

**Comment by luanbach** [comment]
That fixed it. Thank you.
