### ISSUE TITLE
HDR IBL loses energy

### ISSUE THREAD

**Issue by elalish** [google/filament#1387]
**Describe the bug**
A very high dynamic range environment produces a very similar render to the same environment, clipped to standard range (.png). Considering this photo has 21EVs of dynamic range, the vast majority of the energy was removed by clipping, so the resulting renders should have dramatically different brightness. Also, the HDR version should be dominated by the yellow color of the bright sun, but it is blue-gray instead.

**To Reproduce**
1. Download the [Spruit Sunrise](https://hdrihaven.com/hdri/?c=outdoor&h=spruit_sunrise) environment, save the .hdr and also convert to .png (clamped).
2. Run cmgen on each to generate IBLs (I used ktx; if a different option works better, I'd love to know, but I can only import ktx from JS). 
3. Render the [khronos spheres](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres) using each of these IBLs, and no other lighting. I used the node version of filament (1.3.0). Use the same intensity and exposure (I used default exposure and 40,000 intensity). 

**Expected behavior**
Not that model-viewer is a paragon of good rendering yet, but in this case I believe it is more physically accurate than filament, see below. Note that filament's renders in the LDR and HDR cases are in fact different, but very similar.

**Screenshots**
![Screenshot from 2019-07-09 11-46-36](https://user-images.githubusercontent.com/1649964/60929018-71baaf00-a264-11e9-902a-cfeea4189ee8.png)

 - OS: gLinux
 - GPU: NVIDIA Quadro P1000
 - Backend: OpenGL

**Comment by romainguy** [comment]
I'll take a look.

**Comment by romainguy** [comment]
I just tried in our native glTF viewer and once the intensity of the IBL is set to match (just using a digital color picker on the background, so that includes tone mapping) your `<model-viewer>` reference, Filament's rendering is close to Blender's Eevee renderer.

<img width="1136" alt="Screen Shot 2019-07-09 at 6 16 27 PM" src="https://user-images.githubusercontent.com/869684/60933189-1691b800-a276-11e9-8b72-50c89ff05e60.png">

<img width="1552" alt="Screen Shot 2019-07-09 at 6 16 52 PM" src="https://user-images.githubusercontent.com/869684/60933190-172a4e80-a276-11e9-93d5-82bf7665854b.png">

**Comment by romainguy** [comment]
Found the culprit: we clamp env values to 256 max to avoid banding in high frequency env maps. Without this clamping we obtain a result that matches path tracers (I tested with Cycles for instance).

![Screen Shot 2019-07-09 at 6 53 14 PM](https://user-images.githubusercontent.com/869684/60934388-d54fd700-a27a-11e9-9b56-bfd8e8cd804c.png)

**Comment by romainguy** [comment]
TODO: we should window the input before SH projection.

**Comment by romainguy** [comment]
As far as I can tell three.js uses the last MIP level (so a 1x1 cubemap) for diffuse lighting. Windowed SH should give us better results.
