### ISSUE TITLE
gltfio on web: improve support for resource paths

### ISSUE THREAD

**Issue by prideout** [google/filament#1392]
We haven't tested with URL's that have a path components, this is likely broken.

CC @elalish

**Comment by prideout** [comment]
@elalish, I tried two tests by hacking on the `uri` fields `FlightHelmet.gltf`, first I tried replacing `FlightHelmet_baseColor.png` with `foo/FlightHelmet_baseColor.png`, then I tried replacing it with `http://127.0.0.1:8080/foo/FlightHelmet_baseColor.png`.  Both of these worked for me.  What form of URL isn't working for you?

**Comment by elalish** [comment]
The form I was having trouble with was the inverse. Leave all the internal of the gltf alone, but put it in a directory:
../FlightHelmet/
and inside are FlightHelmet.gltf, FlightHelmet_baseColor.png, etc. 

Now try createAssetFromJson('../FlightHelmet/FlightHelmet.gltf'), and I get an error that it can't find <baseURLofWebsite>/FlightHelmet_baseColor.png, because it ought to be looking for <baseURLofWebsite>/../FlightHelmet/FlightHelmet_baseColor.png

**Comment by prideout** [comment]
Ah, thanks, understood.
