### ISSUE TITLE
FBO swapchain?

### ISSUE THREAD

**Issue by gpyalt** [google/filament#1438]
Hi there,

The doc states: "A swap chain represents an Operating System's native renderable surface",
however in practice it seems limited to a window. 

For my application, I would like to have filament render into a FBO, as some additional rendering into the same FBO will be necessary before it is shown to the user. I am wondering how much effort it would be to add this capability to filament?

**Comment by romainguy** [comment]
FBOs are not native renderable surfaces, which is why they are not handled by `SwapChain`. To render into a texture you should use [`RenderTarget`](https://github.com/google/filament/blob/master/filament/include/filament/RenderTarget.h). The render target needs to be set on the `View` (see [`setRenderTarget()`](https://github.com/google/filament/blob/master/filament/include/filament/View.h#L403)).

**Comment by gpyalt** [comment]
Great, many thanks @romainguy.
