### ISSUE TITLE
Handling materials with alpha blend transparency and roughness

### ISSUE THREAD

**Issue by rawnsley** [google/filament#1461]
Consider this [pathological example](https://github.com/google/filament/files/3452334/alpha_test.glb.zip) where the baseColorTexture is a solid orange circle with a transparent background and the roughness is 0.5.

GLTF Viewer (and other online viewers) thinks it looks like this:

<img width="900" alt="Screenshot 2019-07-31 at 15 34 39" src="https://user-images.githubusercontent.com/303516/62220947-c99e8e80-b3a8-11e9-98d1-aca5917c1ea1.png">

But Filament's gltf_viewer thinks it looks like this:

<img width="672" alt="Screenshot 2019-07-31 at 15 35 48" src="https://user-images.githubusercontent.com/303516/62221023-e3d86c80-b3a8-11e9-8228-d5bb352f8930.png">

It appears that most implementations also apply the alpha channel to the light reflected due to roughness, but gltf_viewer apparently treats it like glass with a rough surface (which would reflect light). Both seem equally valid and I can't find anything definitive in the spec regarding how they should be handled.

**Comment by romainguy** [comment]
glTF is unfortunately under specified in that area. Filament does allow to obtain the other behavior by setting the blend mode to "fade" on the material. Our default behavior is to be physically correct (alpha doesn't apply to specular lighting since it's by definition reflected light).

@prideout could you check this glTF file to see if there's a piece of information we're not interpreting right that would help match other viewers?

**Comment by prideout** [comment]
This model uses gltf BLEND which we translate to filament TRANSPARENT (+ depth write enabled) rather than FADE.  I tried FADE and it looked more like Rupert's screenshot, but looks weird at certain angles.

**Comment by romainguy** [comment]
The problem with fade is that it's quite wrong to create glass etc.
