### ISSUE TITLE
gltfio: a problem when loading a model

### ISSUE THREAD

**Issue by Yzou-NaO** [google/filament#1467]
I tried to load a model by gltfio

use other gltf_viewer(**clay-viewer**)
![clay_viewer](https://user-images.githubusercontent.com/39986511/62260051-2cdcff00-b443-11e9-847f-0af8c6b5ebdd.png)
use filament **gltf_viewer**
![gltf_viewer-min](https://user-images.githubusercontent.com/39986511/62260333-30bd5100-b444-11e9-99ff-d55efa7909ce.png)
I also tried to use filament **sample_full_pbr**
![pbr-min](https://user-images.githubusercontent.com/39986511/62260505-b80ac480-b444-11e9-9f2c-1ace5daae8a4.png)

The model looked different only in filament **gltf_viewer**, I'd like to know if this is a bug.

**Comment by prideout** [comment]
Can you attach the glTF file to the issue?

**Comment by Yzou-NaO** [comment]
https://github.com/Yzou-NaO/glTF-Model
Here is the model.
[qingting.zip](https://github.com/google/filament/files/3459440/qingting.zip)
And here is another model which I can't play its animation with filament **gltf_viewer**.

**Comment by prideout** [comment]
Thanks, I can reproduce the animation issue in the qingting model and the specular issue in the rabbit mode.  We'll take a look.

**Comment by prideout** [comment]
@romainguy, the stone rabbit might be a non-bug but I'm not sure yet. You might be interested because the asset seems fine at first glance. It is _not_ using the spec-gloss extension and it provides tangents, a normal map, a metallic-roughness map, and a base color texture. Filament looks more like ThreeJS if I hack our shaders to darken the `baseColor`.  I confirmed that we are setting up sRGB correctly and that the normals/tangents look reasonable.  (Btw I tried to use the new Blender to break apart the GLB, but the exporter failed to preserve tangents and sRGB.)

As for the animation issue in the qingting model, I'll take look at that next.

**Comment by prideout** [comment]
The qingting model has two parallel node hierarchies: one that is rooted into the scene, and one that is orphaned (does not belong to any scene).

The animation is only in the orphaned hierarchy so it gets ignored by gltfio.

Each mesh is referenced by both hierarchies, so applying both sets of transforms seems reasonable.  I'll go ahead and make a fix to ensure consistency with ThreeJS.  I'll also file a Khronos issue because I don't see anything in glTF spec that allows for this, even though Cinema4D apparently relies on this behavior.

(Regarding the rabbit lighting issue, I'm going to set aside since we're not sure it's a bug, we would need to see a comparison that uses the same IBL / light sources.)

**Comment by prideout** [comment]
https://github.com/KhronosGroup/glTF/issues/1649

**Comment by Yzou-NaO** [comment]
Thank you!

**Comment by prideout** [comment]
@Yzou-NaO Given the response to my glTF ticket, unfortunately there is a bug in your asset pipeline (perhaps in an exporter plugin), not in Filament itself.
