### ISSUE TITLE
SSAO Has black artifacts 

### ISSUE THREAD

**Issue by dazcjones** [google/filament#1472]
**Describe the bug**
I am getting black artifacts when I use SSAO.  The lucy_bloom sample (screen shot attached) demonstrates what I am seeing.  In my own code I get these artifacts if I set the rotation on the Indirect Lighting dome to anything other than a multiple of 90 degrees.

**To Reproduce**
1. Run the lucy_bloom demo.

**Screenshots**
![lucy_bloon](https://user-images.githubusercontent.com/7228616/62391269-9c292080-b521-11e9-9863-68be6194bd10.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - GPU: NVIDIA Quadro K2200, K6000
 - Backend: OpenGL
also
 - OS: Windows 10
 - GPU: NVIDIA GTX 980
 - Backend: OpenGL

**Comment by prideout** [comment]
Does this also go away if you disable depth prepass rather than SSAO?

 `view->setDepthPrepass(View::DepthPrepass::DISABLED)`?

**Comment by bejado** [comment]
Probably related to #737

**Comment by dazcjones** [comment]
Yes if I disable the depth prepass it does go away.

**Comment by dazcjones** [comment]
This does seem to be related to #737

**Comment by BStringhamVRSK** [comment]
Some quick, unsolicited advice from someone whose experienced similar problems with other engines:
This is likely due to the shader compiler optimizer creating slightly different code order for geometry calculations during the pre-pass shader than gets created during the secondary passes, _even if the source code for that portion of both shaders is identical_.  I know some compilers have directives that will allow the author to isolate portions of the code during compilation in order to preserve identical results.  I think the MS directive is actually called _**isolate**_, if I remember correctly.

**Comment by romainguy** [comment]
We've been using GLSL's invariant for this but different compilers clearly have different quirks with it. We probably need to sprinkle invariant in other places to help instead of relying on the entire computation chain to be properly handled.

**Comment by prideout** [comment]
We could perhaps use matinfo to analyze the data flow of invarant-qualified variables in SPIRV, much like what I'm currently trying to do with precision qualifiers.

**Comment by romainguy** [comment]
Depth-prepass is now gone and won't cause anymore issues.
