### ISSUE TITLE
Missing SRGB support for DXT compressed textures

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#1497]
**Description**
GLUtils.h seems to be missing support for SRGB textures using DXT compression.  The current code for getInternalFormat shows these cases supported in the switch statement:
    case TextureFormat::DXT1_RGB:          return GL_COMPRESSED_RGB_S3TC_DXT1_EXT;
    case TextureFormat::DXT1_RGBA:         return GL_COMPRESSED_RGBA_S3TC_DXT1_EXT;
    case TextureFormat::DXT3_RGBA:         return GL_COMPRESSED_RGBA_S3TC_DXT3_EXT;
    case TextureFormat::DXT5_RGBA:         return GL_COMPRESSED_RGBA_S3TC_DXT5_EXT;

**Expected behavior**
It appears that **TextureFormat** should also contain definitions:
    TextureFormat::DXT1_SRGB
    TextureFormat::DXT1_SRGBA
    TextureFormat::DXT3_SRGBA
    TextureFormat::DXT5_SRGBA
And would need the corresponding GL types support (GL_COMPRESSED_SRGB_S3TC_DXT1_EXT, etc.).

**Desktop:**
 - OS: Windows 10
 - GPU: AMD FirePro D500 (FireGL V)
 - Backend: OpenGL

**Additional context**
I'm currently working around this with an approximation correction in the shader.  I am also working toward supporting other compression formats, but I thought this apparent oversight was worth your attention.

**Comment by romainguy** [comment]
Thank you! It's either an oversight or because GL ES doesn't support those formats. We'll take a look (or feel free to send a PR if you prefer).

**Comment by BStringhamVRSK** [comment]
I don't currently have a code fix for this, as I'm not sure of what the repercussions are for other platforms within Filament (ie. Vulkan and Metal).  But I would be interested to learn if they are not supported.  

I was going with DXT because the DDS format is convenient, has wide hardware support, and has decent tools support.  Now, I plan on using KTX files with ASTC compression, though I worry that ASTC might have limited hardware support?  Our product is Windows / iOS / Android / Web based.  I'm currently integrating Filament into the Windows piece, with others to follow.  I wish there was a format that worked across all of them.  I would happily take any recommendations you might offer.

**Comment by romainguy** [comment]
If you want a single format I highly recommend you look into [Binomial's Basis](https://github.com/BinomialLLC/basis_universal). We (Google) recently worked with Binomial to open source their encoder and transcoder. The current implementation can transcode to various DXT formats as well as ETC2 which is guaranteed to be supported on all OpenGL ES 3.0 devices. It also supports PVRTC which is available on iOS, and support for ASTC is coming soon.

We'd like to provide a library alongside Filament to make Basis easy to use but in the meantime you can do the integration outside of Filament, you'll just have to choose the target format yourself instead of letting us decide.

**Comment by BStringhamVRSK** [comment]
Thanks for the heads-up!  I will look into that.

**Comment by BStringhamVRSK** [comment]
I have a code fix for this.  I'm waiting for a Contributor Licensing Agreement from my company so I can create a PR.
