### ISSUE TITLE
Vulkan present queue

### ISSUE THREAD

**Issue by bluesky013** [google/filament#1532]
Valid usage of vkGetDeviceQueue in vulkan spec declare "queueFamilyIndex must be one of the queue family indices specified when device was created, via the VkDeviceQueueCreateInfo structure" . Only graphic queue family index was specified when device was created. If present queue family index is not equal to graphic queue family index,  would it be right?

**Comment by prideout** [comment]
I think you're right, to fix this I think we should add the second queue type into our `deviceCreateInfo` struct.  Out of curiosity, is this causing a problem with a certain GPU?

**Comment by prideout** [comment]
This might be non-trivial to fix because the driver API allows clients to do certain things (e.g. upload a vertex buffer) before the swap chain is created.  We need the swap chain in order to have a VkSurface, and we need a VkSurface in order to obtain a present queue family index.

Thankfully, this isn't causing issues on any devices that I know about.

**Comment by prideout** [comment]
@pixelflinger potential starter issue for someone in the Vulkan codebase

**Comment by poweifeng** [comment]
For record: we make the assumption that graphics queues can also present so the two QF index should be the same. If this assumption ever fails, we can revisit.
