### ISSUE TITLE
Cutoff 0.25 test not passing for AlphaBlendModeTest.gltf

### ISSUE THREAD

**Issue by cx20** [google/filament#1572]
**Describe the bug**
I tried to display [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) with filament latest version.
However, it did not pass the `Cutoff 0.25` test.

**To Reproduce**
[filament latest version + AlphaBlendModeTest.gltf result](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.6&type=glTF)

**Expected behavior**
![image](https://user-images.githubusercontent.com/1833979/63893957-698e1d00-ca26-11e9-9eed-2673ca0766c9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1833979/63893983-76ab0c00-ca26-11e9-81af-996a0d6e5408.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1903 (OS Build 18362.295)
- GPU: Intel HD Graphics 520
- Backend: ANGLE
- Browser: Chrome 76

**Comment by prideout** [comment]
This is expected when MSAA enabled.  The glTF spec is ambiguous with respect to ALPHA_TO_COVERAGE:

https://github.com/KhronosGroup/glTF-Sample-Models/issues/221

**Comment by cx20** [comment]
Thank you for telling me that thread. I will look at it.

**Comment by romainguy** [comment]
This test now passes properly.

**Comment by cx20** [comment]
@romainguy I tried the [gltf-test](https://github.com/cx20/gltf-test#feature-test-models) sample again with the [latest build](https://github.com/google/filament/actions/runs/203049248) of Filament. However, the Cutoff `0.25` test result was `0.50`.

[Filament latest version + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/149f2654a0b50629d7ff6014a832547834422980/examples/filament/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/89840042-3cd90400-dbaa-11ea-9e3f-14e8ec70a41c.png)

Is it the wrong way to use it? It would be great to get some advice.

**Comment by romainguy** [comment]
Are you using our main branch?

<img width="926" alt="Screen Shot 2020-08-10 at 4 20 27 PM" src="https://user-images.githubusercontent.com/869684/89840573-6dc32580-db25-11ea-8e6a-e18d81867cf9.png">

**Comment by cx20** [comment]
> Are you using our main branch?

Yes. I used the following build of the `main` branch to try the `WebGL` version of Filament.

![image](https://user-images.githubusercontent.com/1833979/89840966-aa862f80-dbac-11ea-8c77-e7cae3e5d886.png)

**Comment by romainguy** [comment]
@prideout Any idea? My screenshot is from gltf_viewer (native, not WebGL)

**Comment by prideout** [comment]
There's nothing to do here on the Filament side.  When MSAA is disabled, we "pass" the test.  When it's enabled, the rendering is affected by how the browser and GPU implement ALPHA_TO_COVERAGE.

Note that other renderers may or may not enable ALPHA_TO_COVERAGE since this is unspecified in the glTF standard.

It looks like cx20 has MSAA enabled, and is using a browser or GPU that implements ALPHA_TO_COVERAGE strangely.  Not a Filament bug.

**Comment by romainguy** [comment]
Ah right, because when I disable MSAA I get the following in native:

<img width="1136" alt="Screen Shot 2020-08-10 at 5 02 04 PM" src="https://user-images.githubusercontent.com/869684/89842673-39eafe80-db2b-11ea-9640-8cb93a6bb93d.png">

With MSAA:

<img width="1136" alt="Screen Shot 2020-08-10 at 5 02 39 PM" src="https://user-images.githubusercontent.com/869684/89842698-4e2efb80-db2b-11ea-90f1-4c47bf7b9a40.png">

So yeah looks like a browser issue. I guess we could always disable alpha to coverage for glTF but ugh…

**Comment by prideout** [comment]
I don't think we should take any actions until Khronos resolves https://github.com/KhronosGroup/glTF/issues/1668

**Comment by romainguy** [comment]
Not holding my breath :)

**Comment by prideout** [comment]
This bug is 3 yrs old, closing.
