### ISSUE TITLE
Correctly populating MORPH_POSITION and MORPH_TANGENTS attributes

### ISSUE THREAD

**Issue by kylelin47** [google/filament#1602]
Mostly unsure about MORPH_TANGENTS.

It looks to me like MORPH_POSITION is a relative value; applying a morph weight of 1.0 to index 0 means that 100% of MORPH_POSITION_0 is added to the original position of the mesh. So if I want to encode a morph target, I populate MORPH_POSITION with the vertex-by-vertex difference between it and the original mesh.

Given that to be true, how do I properly populate MORPH_TANGENTS? Do I calculate the vertex normals of the "mesh" that is made up of all these relative values? Or do I use the normals of the final mesh I'm trying to end up with?

**Comment by prideout** [comment]
The in-between normals that we compute aren't *strictly* correct because we use component-wise interpolation; however we post-normalize them, so the result looks reasonable.

It might help for you to think of each attribute pair (e.g. POSITION_0 + TANGENTS_0) as an individual mesh that would look reasonable on its own, if it were a non-animated mesh.

In other words, you can simply compute the normals and tangents for each keyframe as you would if it weren't animated.

**Comment by prideout** [comment]
See also #1609, let's move the discussion there.
