### ISSUE TITLE
shader uses same name for variable and function

### ISSUE THREAD

**Issue by attilaz** [google/filament#1659]
https://github.com/google/filament/blob/master/shaders/src/light_indirect.fs#L363

I am trying to convert shaders to https://github.com/bkaradzic/bgfx and ran into a compiler error with this line. This seems to be valid for GLSL input, but I don't think this is a good practice. And invalid for HLSL. I get : 'diffuseIrradiance': identifier represents a variable, not a function. 

And thanks for this great pbr rendering pipeline!

**Comment by romainguy** [comment]
Thanks for the report. This is bizarre limitation of HLSL which doesn't exist in regular languages. Those two names are the best descriptive names I can think of for both the variable and function. Unless this becomes a problem for us I'll leave things this way for now. We translate to other shading languages with glslang and the problem hasn't occurred since it renames variables.
