### ISSUE TITLE
Matching IBL intensity to Blender Environment Texture strength?

### ISSUE THREAD

**Issue by roxlu** [google/filament#1667]
I'm trying to match a scene as much as possible between Blender and Filament. I'm wondering if someone knows how I can map the strength value of the Background node to the IBL intensity value of Filament?

<img src="https://i.imgur.com/6IZIT2l.png" />

The Blender docs don't tell me what unit is used:
https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/background.html?highlight=background

If I'm correct, Filament uses _Luminance_ for this?
https://google.github.io/filament/Filament.md.html#lighting/units

**Comment by romainguy** [comment]
The easiest thing to do to match Blender is to set your camera parameters in Filament so that the exposure is 1. To achieve this use the following settings:

ISO: 100
Aperture: 1.0
Shutter speed: 1.2

With these settings you should be able to use the same strength/intensity as Blender. You can effectively think of these settings as a way to stop using physical light units.

**Comment by roxlu** [comment]
Thanks @romainguy that's perfect.

Does this work the same with the light values that are used in Blender? (I thought they used different units).

**Comment by romainguy** [comment]
If you use these exposure settings, yes, it should work.
