### ISSUE TITLE
Morph shapes not rendering

### ISSUE THREAD

**Issue by elalish** [google/filament#1726]
**Describe the bug**
I'm not getting a render in filament.js for any of the glTF sample models that include morphing. The console (on Chrome) is giving a lot of these: `GL ERROR :GL_INVALID_OPERATION : glDrawElements: vertexAttrib function must match shader attrib type`

**To Reproduce**
You can see our results here: https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html and if you serve model-viewer locally you can also see them live here: http://localhost:8000/test/fidelity/renderers/filament/

The problem models are khronos-AnimatedMorphCube, khronos-AnimatedMorphSphere, and khronos-MorphPrimitivesTest

**Comment by prideout** [comment]
Yup, these models work with OpenGL but not WebGL.  I'll look into it.

(Buster Drone is my favorite model that has morphing)

**Comment by prideout** [comment]
Our skinning-and-morphing material variant consumes the BONE_INDICES vertex attribute, so when a model uses only morphing our Vulkan / Metal backends supply a correctly-typed dummy attribute. 

However, our OpenGL / WebGL backends do not require a dummy attribute because those API's provide a default data stream of all-zeroes.  The default data stream is apparently float-typed, which breaks WebGL's strict typing rules since our vertex shader consumes `uvec4`.

We could fix this in gltfio by providing a dummy buffer, but I think it might be better to provide a #ifdef'd fix in the GL backend so that other clients like Sceneform can leverage the fix.

**Comment by elalish** [comment]
@prideout Can you reopen this? I just pulled in filament.js v1.4.1 and there's no change; same behavior, same error.
