### ISSUE TITLE
How to lock vertex data from Entity?

### ISSUE THREAD

**Issue by Realitian** [google/filament#1755]
Hi, how can lock vertex buffer and get vertex data from Entity instance?
I tried to load glft file and I have the pointer of gltfio::FilamentAsset, but I need to hit test per triangle face for loaded gltf mesh.
How can get vertex data from asset or Entity?
Cheers!

**Comment by Realitian** [comment]
Sorry, stupid question.
I think to use FilamentAsset::getBufferBindings.

**Comment by prideout** [comment]
If you're using C++ you can call `loadResources()` then look at the `data` pointer in the buffer bindings that are exposed by `FilamentAsset`.  Do not call `releaseSourceData` until after you're done reading all the data you need.

**Comment by Realitian** [comment]
`data` is the pointer of struct `cgltf_data` from https://github.com/prideout/cgltf/blob/master/cgltf.h ?

**Comment by prideout** [comment]
Actually it's just the raw data, it's a reference to the data field in a `cgltf_buffer` struct.

**Comment by Realitian** [comment]
`data` pointer was some misunderstanding, can you explain how to get triangle list from `data`?

**Comment by prideout** [comment]
If you know which buffer binding corresponds to POSITION and the data format, you could read the values that are pointed to by `data` member.

However, since it's not likely that you know that information a priori, I have a new suggestion :)

My new suggestion is to call `filamentAsset->getSourceAsset()` and cast it to `const cgltf_data*`, which gives you access to the entire glTF file.  From there you should be able to get to the accessors for positions and indices.  You can use `cgltf_accessor_read_float()` and `cgltf_accessor_read_index()` to extract data from those accessors.  For more information, refer to `cgltf.h`.  You'll need to do all this after calling `loadResources()` but before calling `releaseSourceData()`.

It's not simple but at least it's possible.  The gltfio library was originally meant only for rendering glTF files, so this is a new use case.

**Comment by Realitian** [comment]
Thanks.
