### ISSUE TITLE
Lots of build-generated files are not in .gitignore

### ISSUE THREAD

**Issue by Reedbeta** [google/filament#1771]
Building on Windows using MSVC 19 backend. As soon as you just generate build files in CMake, git shows hundreds of files generated by the build that are not ignored by the .gitignore. And when you actually build in MSVC there are even more.

**Comment by romainguy** [comment]
Thanks for the report. Where do you generate build files? We use out/ by default and that's in our gitignore.

**Comment by Reedbeta** [comment]
Do you mean where do I set the "where to build the binaries" option in CMake? I usually set it to the same directory as the source. If it's expected to set it to out/ that's fine, though should ideally be noted in the build instructions in the readme.

**Comment by romainguy** [comment]
All our instructions in the root README use out/. We can make it more explicit. @bejado can you handle this please? We should also cleanup the Windows section to make it simpler since llvm isn't required anymore.

I guess I'm used to never generating CMake build files in the source tree in any project specifically because of what you're running into ^^ CLion will use $root/cmake-build-release and -debug which are also in .gitignore.

**Comment by Reedbeta** [comment]
Ahh, yeah, the instructions don't really explicitly tell you how to configure it, especially if you're using the CMake GUI.

**Comment by romainguy** [comment]
We should fix that then :)

**Comment by bejado** [comment]
We now have a [section](https://github.com/google/filament#building-on-windows-with-the-visual-studio-2019-compiler) in our README that explains building with VS2019.
