### ISSUE TITLE
Support GLTF files in the Android bindings

### ISSUE THREAD

**Issue by ansman** [google/filament#1841]
Even though it should be preferred to use GLB for performance it's useful to be able to use GLTF during development.

**Comment by romainguy** [comment]
This is not about performance but about simplicity. glTF assets use multiple files which forces to have a more complex API to load them (since they could be resources, assets, files, streams, etc.). The proper way would be to have the client app supply some kind of callback that Filament would invoke when wanting to load a particular file.

**Comment by prideout** [comment]
The only thing missing is exposing `ResourceLoader::getResourceUris` to Java and adding to the usage example to the javadoc.

Java and JavaScript clients are expected to call `getResourceUris`, then `addResourceData` to supply externally-referenced data.  Desktop clients don't need to do this since there is a filesystem.

**Comment by prideout** [comment]
There are some outstanding tasks needed to get this to work, reopening.
