### ISSUE TITLE
Horse.glb does not animate correctly

### ISSUE THREAD

**Issue by cx20** [google/filament#1852]
**Describe the bug**
I tried to display the [horse model](https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Horse.glb) in the latest version of Filament.
https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Horse.glb
However, it does not seem to animate correctly.

**To Reproduce**
[Filament + Hourse.glb result:](https://rawcdn.githack.com/cx20/gltf-test/53d24ea498413ad6b1c1f93a1a9e00afa5154d90/examples/filament/index.html?url=https://rawcdn.githack.com/mrdoob/three.js/aea0b4bc96a340cc0bc420971efe71ed5194062b/examples/models/gltf/Horse.glb&scale=0.01)
![filament_Horse](https://user-images.githubusercontent.com/1833979/68300430-177e0d80-00e1-11ea-9483-94368e793bfc.gif)

**Expected behavior**
[three.js + Hourse.glb result:](https://rawcdn.githack.com/cx20/gltf-test/53d24ea498413ad6b1c1f93a1a9e00afa5154d90/examples/threejs/index.html?url=https://rawcdn.githack.com/mrdoob/three.js/aea0b4bc96a340cc0bc420971efe71ed5194062b/examples/models/gltf/Horse.glb&scale=0.01)
![three_Horse_20190302](https://user-images.githubusercontent.com/1833979/68300464-295fb080-00e1-11ea-8154-0515fd8beb91.gif)

**Desktop (please complete the following information):**
- OS: Windows 10 + Chrome 78
- GPU: Intel HD Graphics 520
- Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by prideout** [comment]
This mesh has 15 morph targets but Filament only supports 4 morph targets right now.  See also #1487.

As an aside, this mesh does not have normals.

**Comment by donmccurdy** [comment]
> This mesh has 15 morph targets but Filament only supports 4 morph targets right now.

Note that three.js also does not support more than 4-8 morph targets, but automatically selects the morph targets with the highest weights if there are more than can be applied. For this style of animation (which is basically an MDD file baked into a glTF morph target sequence) there are never more than ~2 morph targets active at a time, so selecting the highest weight targets works well.

**Comment by prideout** [comment]
@donmccurdy very interesting, thanks!  That makes sense but it is not super easy to implement for us (*), so we need to decide if it is worthwhile.  Does the glTF spec recommend the fallback behavior that you describe?  Does it occur frequently out in the wild?

(*) Our gltfio library would need to construct new `filament::VertexBuffer` objects on the fly (which is our notion of an VAO) since every `filament::VertexBuffer` can have only 4 morph attributes, and we wouldn't want to create one at load time for every combination of weights.  Since this would be prohibitively expensive, we would also need to consider enhancing Filament itself, since it currently only permits mutation of a `filament::VertexBuffer` via glBufferSubData.

**Comment by donmccurdy** [comment]
The glTF spec requires only that `A conformant client implementation must support at least eight morphed attributes`, so you're already within the spec's requirements already. 👍 

I don't think it's a particularly common style of animation, but I occasionally see Blender users baking animations this way. There are a bunch of examples here: https://mrdoob.github.io/rome-gltf/. All of those examples would probably have been just as well served by skinning, but there are other cases where this animation style comes in handy that skinning might not handle so easily, like a cloth animation.
