### ISSUE TITLE
GPU is doing unnecessary work when skybox is enabled.

### ISSUE THREAD

**Issue by prideout** [google/filament#1914]
If you run the **image-based-lighting** sample with enhanced systrace, you'll see lots of 
 "unresolve" events (GMEM loads).  These go away after removing the following line from MainActivity.

```kotlin
scene.skybox = ibl.skybox
```

Each unresolve seems to consume more than one-third of all GPU work in each bin, so it would be good to fix this up.

**Comment by romainguy** [comment]
The skybox is just a regular draw call, removing it will allow the GPU to not resolve tiles where we don't draw anything. Not sure there's an actual issue here.

**Comment by prideout** [comment]
Yes but the unresolve events seem strange since we do not need to preserve framebuffer content.  Blending is disabled so we should discard the existing content.

**Comment by pixelflinger** [comment]
No actually the skybox is special because it deactivates the clear, and the framegraph has a special case when clear is activated, it always forces a discard. I think we introduced a bug where the discard flags are either not set properly or not taken into account.
When drawing the first view, whether we clear or draw the skybox, we shouldn't reload the tile, I can't see why we'd even need the (unknown) content of the framebuffer (even with blending actually).
