### ISSUE TITLE
Duplicate symbol with libfilamat.a on macOS

### ISSUE THREAD

**Issue by yongtang** [google/filament#1942]
**Describe the bug**

While trying to link with pre-built macOS release libraries (`filament-20191127-mac.tgz`), the following error show up:
```
duplicate symbol 'spv::Parameterize()' in:
    external/filament/lib/x86_64/libfilamat.a(libSPIRV_doc.cpp.o)
    external/filament/lib/x86_64/libfilamat.a(libSPVRemapper_doc.cpp.o)
duplicate symbol 'spv::CapabilityString(int)' in:
    external/filament/lib/x86_64/libfilamat.a(libSPIRV_doc.cpp.o)
    external/filament/lib/x86_64/libfilamat.a(libSPVRemapper_doc.cpp.o)
duplicate symbol 'spv::MemoryString(int)' in:
...
...
```

I am not familiar with CMake though looking through the lines in:

`third_party/glslang/SPIRV/CMakeLists.txt`

I am wondering if the error is caused by `doc.cpp` file is included in both `SOURCES` and `SPVREMAP_SOURCES`?

**To Reproduce**

I am using Bazel to link pre-built filament libraries  (`filament-20191127-mac.tgz`) to a program. If it helps, I can try to come up with a minimal reproducible example to show the error.

**Expected behavior**

No `duplicate symbol` error when linking pre-built filament libraries .

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - GPU: n/a
 - Backend: n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a

**Comment by bejado** [comment]
Can you show the compiler / linker invocations used to link against `libfilamat.a`? We link against it ourselves in several places, such as the `matc` tool, so this is a peculiar find.

**Comment by yongtang** [comment]
Thanks @bejado, I am trying to build a shared library (.so) with `libfilamat.a`. So it might be different from building a binary.

I created a small reproducible repo:

https://github.com/yongtang/graph

To repeat the issue (On macOS Catalina):

1) Install the Bazel (I am using 1.2.0) from https://github.com/bazelbuild/bazel/releases/tag/1.2.0 
2) Run the following command:
```
bazel build -s --verbose_failures  //...
```

Then the following will show up:
```
duplicate symbol 'spv::Parameterize()' in:
....
...
```

**Comment by bejado** [comment]
The duplicate symbols are being caused by the `-Wl,-force_load,` compile flags before `external/filament/lib/x86_64/libfilamat.a`. Indeed the libraries `libSPIRV` and `libSPVRemapper` have duplicate symbols.

We link `libfilamat.a` into a JNI shared library but don't see the errors because the linker is free to strip unused symbols (I guess our JNI library isn't using those symbols). The `-force_load` flag tells the linker to load _all_ symbols, and it has no choice but to complain about the duplicates.

Maybe bazel has a way to not force load symbols?

Note that you don't need to link against `libfilamat.a` unless you want to compile materials programatically. You can use the `matc` tool to precompile.

**Comment by yongtang** [comment]
@bejado I haven't found the way to configure Bazel to not force load symbols, though indeed after removing `libfilamat.a` the build works correctly. 👍 ❤️  Thanks for the help and really appreciate that!
