### ISSUE TITLE
Disable frame-skipper for offscreen rendering

### ISSUE THREAD

**Issue by danlehmann** [google/filament#2011]
I am building an artificial life simulation where I am using Filament to render eye buffers of virtual creatures. To do this, I am setting up the Filament scene and then render with a different cameras for each creature into its off-screen buffer, that is then passed to the creature's brain.

The main loop looks something like this:

while (1) {
  setupFilamentScene()
  for (animal <- world) {
    filament.camera = animal.camera
    filament.renderer.beginFrame()
    filament.renderer.render()
    filament.renderer.readPixels(animal.swapChain, onFinish: {
      animal.eyes = buffer
      animal.think()
      animal.act()
    })
    filament.renderer.endFrame()
  }
}

Things in general work, but beginFrame() often returns false. This might be useful for displaying things on screen, but for my use-case, skipping frames is never the right thing. I tried the following:

a) Loop until ready
    while (!renderer.beginFrame(renderBuffer.swapChain)) {
      Thread.sleep(1)
      waited += 1
    }

b) Instantiate more than 1 Renderer
c) Disable calls to mFrameSkipper inside of Renderer.cpp

Using option a), I am getting about 2000 images/sec. Using option b or c, this goes up to about 3600 images/sec. Still far below what I'd like to see, but almost 2x as good.

**Describe the solution you'd like**
I think being able to render into offscreen buffers as quickly as possible is a use-case that would also be interesting for other people. So I am wondering if there is a good way to generalize this.

Would it make sense to add a "disableFrameSkipper" (or similar) property to Renderer?

In my testing it was enough to simply skip over https://github.com/google/filament/blob/fddf51dc74edcaf1f0ba64349fbc7ca89a228404/filament/src/Renderer.cpp#L523:L528
and https://github.com/google/filament/blob/fddf51dc74edcaf1f0ba64349fbc7ca89a228404/filament/src/Renderer.cpp#L558, but I am not familiar with the inner workings of the engine, so I don't know what side-effects this might cause. If this sounds like a sane thing to do, I can upload a patch to add that property.

**Describe alternatives you've considered**
I successfully created multiple Renderers to overcome this problem, but that seems like a hacky workaround.

**OS and backend**
Not OS specific.

**Comment by pixelflinger** [comment]
Hi. This seems a very cool use of Filament :-)  I'd like to see the renders!

For you use-case you can simply ignore the result of beginFrame() -- you'll need some kind of flow control though, so that you don't saturate the internal command buffer (e.g. if you're rendering much slower than you're pushing frames). But you sort of already have that, because you have the readPixels() callback. 

The readPixels() callback currently triggers after the GPU is finished, which might be too late for you, however you could use a `Fence` after each frame you push, the Fence will trigger when the commands have been executed up to that point -- this should allow you to devise a flow control system (e.g. maybe enqueue up to N frames at a time).

Note: the FrameSkipper doesn't regulate anything internally -- it's just informative. It just tells you that you've Enqueued 2 frames and that the first one is not finished (on the GPU) yet. You're free to ignore it.

**Comment by danlehmann** [comment]
Thanks, ignoring the result of beginFrame works fine and improves perf nicely.

Your fence suggestion is also useful. Given the low number of creatures I have at the moment I don't need it yet, but as the world grows this sounds like a system I'll need to implement. Thanks!

And I'm happy to share the results, once all of this looks a little nicer :-)
