### ISSUE TITLE
cmgen generated filename had changed in generally?

### ISSUE THREAD

**Issue by Realitian** [google/filament#2084]
looks like cmgen generated filename had changed in generally.(i.e. generated_ibl.ktx, generated_skybox.ktx, etc).
in previous version, it works with prefixed with original hdr filename, so it was help when does batch process. but with current version, I was difficult to run batch process shell because cmgen generate same filename for different .hdr files.
I am sorry for telling about additional issue, but just wanted to recommend that the old version is more useful.

**Comment by prideout** [comment]
Yes,  #1974 made it so that scripts no longer need to manually rename the output folder when generating multiple variants of the same KTX (e.g. for compressed and non-compressed variants).  You can still prefix the original hdr filename if you like, but it's now optional rather than forced.  If your old script said `-x dest source.hdr`, your new args can simply be `-x dest/source source.hdr`.
