### ISSUE TITLE
Support for ANGLE

### ISSUE THREAD

**Issue by strentler** [google/filament#2390]
Filament does already support for many graphics APIs, but DirectX is missing. 

I wonder why do you not support the graphics abstraction layer ANGLE? This would include support for many graphics APIs including DirectX. 

Why did you not choose ANGLE right from the beginning?

**Comment by romainguy** [comment]
ANGLE is larger than we want and does more than we want. It also didn't properly support ES 3.0 ad 3.1 when we started. But since Filament supports GLES there's no reason you can't use ANGLE. Although I'm not sure what the point would be since both OpenGL and Vulkan are supported on Windows.

**Comment by strentler** [comment]
OpenGL and Vulkan is not supported on all hardware from Microsoft. They only support DirectX on such hardware. ANGLE would close this gap. Other option would be native support in filament for DirectX.

**Comment by romainguy** [comment]
What hardware does not support GL nor Vulkan?

**Comment by strentler** [comment]
@romainguy. For example the Hololens.

**Comment by codeandroid** [comment]
> Although I'm not sure what the point would be since both OpenGL and Vulkan are supported on Windows.

I would like to provide another use case. It might not be relevant to your regular user base, but it is very relevant to our customers - especially those working from home, accessing HPC machines or virtual machines on public clouds remotely.

Graphics hardware acceleration over Microsoft's Remote Desktop Protocol (RDP) generally only works correct if Direct3D is used (for example via ANGLE) or in a few very specific edge cases (like NVIDIA Quadros on both sides of the connection and since April 2, 2020 also for Geforce with a new driver).
Regular "Desktop OpenGL" is typically a very large issue as Microsoft does not pass through the driver but limits the driver to a very old Microsoft OpenGL driver - so it's effectively not available.

Interestingly enough, in recent years, due to increasing popularity of laptops, work from home scenarios and public cloud VMs, this is so important to our customers, that for a new visualization package we began building on ANGLE (and will probably switch to one of the webgpu implementations in the future - Google Dawn or Mozilla gfx-rs webgpu). If there was a renderer supporting ANGLE... ;)

PS: We also compile with Emscripten so WebGL (or WebGL 2) is a set baseline, anyway.

**Comment by romainguy** [comment]
Dawn/WebGPU is something we plan on doing.
