### ISSUE TITLE
mipgen linearized/srgb issue

### ISSUE THREAD

**Issue by EvilTrev** [google/filament#2422]
It looks like if you are writing ktx with astc compression from mipgen, that the `.srgb` parameter in the astc configuration is not initialized or set? In the case of a non-ktx file, `g_linearized` is used to decide if the final data output is `fromLinearToRGB` or `fromLinearTosRGB`... however I don't see matching logic to control astc output from ktx code. I think the files are always being created as linear, which would be a quality loss for color images.

Perhaps I'm missing something somewhere, but it seems like a line along the lines of:
```
config.astc.srgb = !g_linearized;
```
is required after `parseOptionString` to output the correct color space? Or perhaps input params for astc compression need expanding to `astc_[fast|thorough]_[srgb|linear]_[ldr|hdr]_WxH`?

**Comment by prideout** [comment]
Correct, sRGB has not been implemented in the ASTC path, I had set aside working ASTC due to flakiness and crashes in ARM's encoder library.  Side note: the library has been rewritten and it we need to upgrade to the new version.

Another thing in my notes is that we do not support non-divisible-by-4 textures in the ASTC path.

Related issue: we also were not honoring the format in the KTX file until https://github.com/google/filament/pull/4039

I'll look into this.
