### ISSUE TITLE
Android API 19 support

### ISSUE THREAD

**Issue by aleyooop** [google/filament#2492]
Referring the commit [1366602](https://github.com/google/filament/commit/13666027ccdc37c1f7dfb54dc6c9e925bb61e761#diff-7ae5a9093507568eabbf35c3b0665732) native code API level switched back to 21.
When trying to build for API 19 (sample-gltf-viewer), link error occurs:
```
java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libgltfio-jni.so" needed by "libfilament-utils-jni.so"; caused by cannot locate symbol "atof" referenced by "libgltfio-jni.so"
```

So I tried to switch API level to 19, next error is:
```
java.lang.UnsatisfiedLinkError: Native method not found: com.google.android.filament.gltfio.MaterialProvider.nCreateMaterialProvider:(J)J
```

This one is fixed by calling `Gltfio.init()` along with `Utils.init()`
Then I'm getting some of:
```
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon: glUtilsParamSize: unknow param 0x0000821d
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetStringi:3762 GL error 0x501
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetStringi:3762 GL error 0x501
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetStringi:3762 GL error 0x501
...
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetStringi:3762 GL error 0x501
```

And then a bunch of repeating non-stop:
```
W/Filament: no texture bound to unit 0x4
W/Filament: no texture bound to unit 0x5
W/Filament: no texture bound to unit 0x6
W/Filament: no texture bound to unit 0x7
...
W/Filament: no texture bound to unit 0x4
W/Filament: no texture bound to unit 0x5
W/Filament: no texture bound to unit 0x6
W/Filament: no texture bound to unit 0x7
```

 - Device: [Android Emulator], GLES3.0
 - OS: [API 19]

The reasonable question is why native code API switched to 21 when min supported is 19 and if there any way to fix all compatibility issues?
Maybe I'm doing something wrong?
Thanks!

**Comment by romainguy** [comment]
The "no texture bound" issues are unrelated. gltfio should be binding textures to unused slots. The other errors you're showing are from the emulator right? They happen on all API levels and they're an emulator implementation issue.

As for using 21 with the NDK it shouldn't be an issue as we take care of not calling missing native APIs inside the engine itself. This was required to get the native binaries to behave properly on newer versions of Android.

Anyway the only real issue you're running into is:
`java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libgltfio-jni.so" needed by "libfilament-utils-jni.so"; caused by cannot locate symbol "atof" referenced by "libgltfio-jni.so"`

The rest can be safely ignored. I don't know what's causing this, `atof` is definitly part of the runtime on 19.

**Comment by aleyooop** [comment]
Yes, all of the issues are from emulator.
Something similar also occurs on material builder sample:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "localeconv" referenced by "libfilamat-jni.so"
```

To reproduce both, simply build on x86 emulator with API 19

**Comment by romainguy** [comment]
I'll check it out when I have some time but we may simply drop API level 19 support.

**Comment by aleyooop** [comment]
Ok, thanks anyway

**Comment by romainguy** [comment]
At this point we won't try to support API level 19 anymore, sorry about that :(
