### ISSUE TITLE
Improvements to the standard model summary

### ISSUE THREAD

**Issue by ApoorvaJ** [google/filament#2511]
In Listing 9 in the [Standard model summary](https://google.github.io/filament/Filament.md.html#materialsystem/standardmodelsummary), I'd suggest two changes. Feel free to close the issue if you disagree.

1. For `F_Schlick()`, the function signature is `vec3 F_Schlick(float VoH, vec3 f0)`, but the usage is `vec3  F = F_Schlick(LoH, f0)`. In the [Frostbite document](https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf)'s Disney diffuse BRDF, listing 1, it is called twice more, with `NoL` and `NoV`. My proposal: Either rename `VoH` in the function signature to `LoH`, or to something like `u`, as seen in the Frostbite document, listing 2.

2. Below the comment `// apply lighting...`, it might be worth alluding to the fact there's a final multiplication by n dot l. This is mentioned a lot later in the [direct lighting section](https://google.github.io/filament/Filament.md.html#lighting/directlighting/directionallights)'s equation 56, but speaking from personal experience, a note in the summary might save a lot of troubleshooting for folks incrementally implementing PBR.

**Comment by romainguy** [comment]
`h` being the half vector between `v` and `l`, `LoH` and `VoH` are interchangeable. I did rename it to `u` just because we also show the Disney's diffuse BRDF which uses `NoL` and `NoV`.

`NoL` is *not* part of the BRDF and that's why it is not shown in that first section. I'm not sure how to introduce it there in a meaningful way. You can't really use the BRDF as is without understanding the lights themselves.

**Comment by romainguy** [comment]
https://github.com/google/filament/commit/91f052a9b0ce06fde387018e846ec0c8f064a6ff
