### ISSUE TITLE
View.sampleCount not applied when post-processing disabled

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2533]
There is code [in the Renderer](https://github.com/google/filament/blob/master/filament/src/Renderer.cpp#L418) to handle MSAA when rendering directly (i.e. no post-processing), but there is [also code that overrides the sample count](https://github.com/google/filament/blob/master/filament/src/Renderer.cpp#L212) when post-processing is disabled. MSAA appears to work if you remove that line, but I'm not sure if there are consequences I am missing.

Related: are their performance implications to using textures for MSAA rather than just enabling EGL_SAMPLE_BUFFERS when the EGL context is created? I can't quite work out what the [opaqueBlit](https://github.com/google/filament/blob/master/filament/src/PostProcessManager.cpp#L478) function actually does.

**Comment by romainguy** [comment]
The problem with MSAA is that it has to be treated completely differently depending on whether you render to the EGL surface directly or not. Handling both cases is quite a pain especially since turning MSAA on/off (or changing the sample count) requires recreating the EGL configuration/context. Our current solution is to only use MSAA via textures to simplify the backend implementation.

@pixelflinger

**Comment by pixelflinger** [comment]
Yeah this one is kind of weird.  So initially, I chose to disable MSAA when post-processing was disabled because in that case we would render directly into the EGL surface, and it would not have been created with MS. 
But then, later we added the ability to disable tone mapping separately (which is kind of weird, because that also disables dithering and bloom), and that could result in the same issue, so we had to fix it by adding a "fake" blit (just so was have an intermediate buffer).

So in fact, now, MSAA should work even when post-processing is disabled -- but it will create a temporary buffer.

So it's really an API decision at this point. I think there is some value in disabling everything "costly" when post-processing is disabled.  And you can accomplish the same thing by turning off all post-processing components independently.

I will think more about it. Thanks for reporting it.

`opaqueBlit` just copies a buffer + optional resize. In the case of MSAA without any other post-processing, we add an extra `opaqueBlit` just so we have an intermediate buffer -- because we cannot draw in multisampling into the EGL surface (because it's not created with multisampling). 

While on the subject, please be aware that MSAA can become extremely costly when screen-space refraction is enabled.
