### ISSUE TITLE
Using from emscripten without JS wrappers

### ISSUE THREAD

**Issue by kpeeters** [google/filament#2546]
I am trying to use filament on the web directly from emscripten-compiled C++ code, without going through the JS wrappers (as I already have all the Filament-related logic in C++), but am stumbling on a small problem. Basically, I first setup the GL context with

    EmscriptenWebGLContextAttributes attributes;
    attributes.alpha=true;
    attributes.majorVersion=2;
    attributes.minorVersion=0;
    attributes.antialias=true;
    attributes.depth=true;
    
    context = emscripten_webgl_create_context("#canvas", &attributes);
    emscripten_webgl_make_context_current(context);
 
That works fine (return of the last call is EMSCRIPTEN_RESULT_SUCCESS). I then set up the Filament renderer with

    engine = filament::Engine::create();
    swapchain = engine->createSwapChain(nullptr);
    renderer = engine->createRenderer();

in particular I do *not* feed anything but a `nullptr` into `createSwapChain`, as that is what your JS bindings seem to do. Now the render loop looks like

    if(renderer->beginFrame(swapchain)) {
        renderer->render(view);
        renderer->endFrame();
    }
    engine->execute();

with the last line to take into account that this is a single-threaded platform.

When executing this, I get

    GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClearBufferfv: framebuffer incomplete
    GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawElements: framebuffer incomplete

So I am obviously missing some step somewhere in the initialisation. Any ideas? Thanks!

**Comment by prideout** [comment]
Interesting...  In your console, do you see `FEngine (32 bits) created at 0x632e70 (threading is disabled)`?

**Comment by prideout** [comment]
Another idea to obtain clues is to force-enable our GL error catching code in `GLUtils.h` by removing the first 7 lines from the following code block.

```
#ifdef NDEBUG
#define CHECK_GL_ERROR(out)
#define CHECK_GL_FRAMEBUFFER_STATUS(out)
#else
#ifdef _MSC_VER
    #define __PRETTY_FUNCTION__ __FUNCSIG__
#endif
#define CHECK_GL_ERROR(out) { GLUtils::checkGLError(out, __PRETTY_FUNCTION__, __LINE__); }
#define CHECK_GL_FRAMEBUFFER_STATUS(out) { GLUtils::checkFramebufferStatus(out, __PRETTY_FUNCTION__, __LINE__); }
#endif
```

**Comment by kpeeters** [comment]
Yes, the `FEngine` startup message is there. Those additional options make no difference (and were in fact only a recent addition to your `CMakeLists.txt`; they are not in 1.6.0). I'll try to see if enabling GL error checking produces more useful info. Thanks for the pointer.

Perhaps related: I noticed that I had to turn on `-s FULL_ES3` in order to avoid linking errors (missing symbols). You don't seem to have that anywhere in your `CMakeLists.txt`.

**Comment by prideout** [comment]
Nice, I didn't know about `FULL_ES3`, we were getting around this by disabling ERROR_ON_UNDEFINED_SYMBOLS.

I'm stumped by your problem, but this is a scenario that we'd like to support.  Feel free to send code or details on how I could go about reproducing this.

**Comment by prideout** [comment]
@kpeeters have you had any luck with this?  If you can construct a small repro app, then I would be happy to investigate.

**Comment by kpeeters** [comment]
@prideout Have been tied up with other things, will have a closer look again this weekend.

**Comment by kpeeters** [comment]
Using a filament build with those 7 lines commented out produces the following error:

    COMPILE ERROR:
    ERROR: 0:275: 'fragColor' : must explicitly specify all locations 
                                when using multiple fragment outputs

The shader code follows (can send that if the above does not ring any bells).

**Comment by prideout** [comment]
Interesting, this helps.  So I think this bug has more to do with our WebGL 2.0 support, not with using C++ vs JS.  Out of curiosity, what features are you enabling in your `View`?  e.g. do you have Depth of Field enabled?

**Comment by kpeeters** [comment]
The only things I do with my `View` is to call `setViewport` and `setBlendMode(filament::View::BlendMode::TRANSLUCENT)`. Will try removing the latter (though I really need it).

**Comment by prideout** [comment]
Thanks.  I think our post-processing pipeline is causing this on your machine even though I'm not seeing it with Chrome 81 + macOS 10.15. (btw you can disable post-processing on the View, as an experiment)  It might also be interesting for me to see the contents of `chrome://gpu`, which you can attach to this bug report.

**Comment by kpeeters** [comment]
[gpu.txt](https://github.com/google/filament/files/4683913/gpu.txt)

Bog standard integrated Intel GPU, see attached. Will try disabling post-processing later tonight, thanks.

**Comment by kpeeters** [comment]
Interesting. When I disable postprocessing, I *still* get that error message, but the rendered view shows up, and my rendering loop runs (that is, the error is not fatal). Turning off `TRANSLUCENT` blend mode makes no difference. The error message only appears once.

**Comment by prideout** [comment]
The error message says that the layout location isn't explicitly specified, which might indicate that you're using a material that has been compiled for Desktop rather than Mobile.

Make sure that `IS_MOBILE_TARGET` is enabled in your top-level CMakeLists when building Filament, and make sure that you're using `-p mobile` when invoking matc.

**Comment by kpeeters** [comment]
I am doing both but still seeing the error. Is https://github.com/google/filament/issues/2688 related?

**Comment by prideout** [comment]
Interesting, that bug is possibly related but I'm not sure. Note that we've recently made many changes to both DoF and matc, can you try again with the latest Filament source?  If the error still occurs, we can re-open the bug.  Please post the newly annotated error messages.  Also feel free to change the bug title since I think this is unrelated to our JS bindings.

Also, if there were any way for me to repro, it would be great.

(As a side note, you might need to disable SSAO, see #2338.)

**Comment by kpeeters** [comment]
Works without errors in 1.7.0, thanks!

**Comment by AThilenius** [comment]
This is exactly what I'm looking for! @kpeeters any chance you could share a quick how-to on linking Filament with a WASM target? I assume you have to use Emscripten and can't use LLVM for this (I'm not familiar enough with WASM to fully grok this one).

My use case is a tad more complicated because I would like to use Filament from Rust (which is an LLVM language). There is pretty extensive C-linage support though. I made [filament-rs](https://github.com/AThilenius/filament-rs) a while back to play with both low and higher level Rust bindings, but it was native. Would love to get that working in Web/WASM!
