### ISSUE TITLE
Principled bsdf features doesn't work in filament

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2631]
hi, I export a glb mesh with "transmission" enabled from blender but I can not see transmission effects in filament. (After refering to the The material guide I found the RefractionMode should be set. But the material of glb is built automatically and I can not find a "setRefractionMode()" function in material instance.).  Is there an exporter for filament to achieve WYGIWYS?  Or any best practices to make gltf models to achieve full features of filament? 
(ps: Some features like RefractionType(thin/solid) cannot be found in Blender's standard Principled BSDF material slots, too.)
thanks!!
[monkey.glb.zip](https://github.com/google/filament/files/4720938/monkey.glb.zip)
![image](https://user-images.githubusercontent.com/5915889/83593956-8f85b680-a590-11ea-87ac-b210ea54245e.png)
![image](https://user-images.githubusercontent.com/5915889/83594238-4bdf7c80-a591-11ea-925e-3c447f317a39.png)
![image](https://user-images.githubusercontent.com/5915889/83594204-366a5280-a591-11ea-9bde-3cec08076c16.png)

**Comment by romainguy** [comment]
glTF does not support all the features of the Principled BSDF node of Blender. There are extensions under discussion to make IOR, transmission, etc. available though. To use features not available in glTF you'll have to create your own materials. Things like refraction, etc. cannot be enabled at runtime on a material because they change the code that needs to be generated in the shaders.
