### ISSUE TITLE
Objects behind occluded object shows artifacts

### ISSUE THREAD

**Issue by balarayen** [google/filament#2636]
**Describe the bug**
When applying occluder material to a glb floor object and then making some column objects to animate from the bottom. The portion of the column under the occluded floor object is visible and randomly shows artifacts as shown in the screenshot.

I'm using filament version 1.4.5 with cherry-picked merges(#2582) compatible to sceneform v1.16.

1. How can I hide the portion of the column object under the occluded object without artifact?
2. Is there any fix available for this issue in the latest version that I can cherry pick?

**Screenshots**
<img width="264" alt="Screenshot 2020-06-04 at 7 20 32 AM" src="https://user-images.githubusercontent.com/15100341/83705949-e5f80100-a633-11ea-8031-477334f52269.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Comment by romainguy** [comment]
What is the occluder material and do you know in which order (priority) the objects are rendered?

**Comment by balarayen** [comment]
This is the occluder material:

```
material {
    "name" : "Face Mesh Occluder",
    "parameters" : [
        {
            "type" : "float",
            "name" : "unused"
        }
    ],

    "shadingModel" : "unlit",
    "colorWrite" : false,
    "depthWrite" : true,
}

```
Rendering priorities:
1. Camera stream : 0 (first)
2. Floor object: 1 (second)
3. Column objects: 4 (third)

**Comment by romainguy** [comment]
See bug #2641 as well.

**Comment by jiqimaogou** [comment]
https://github.com/google/filament/issues/2641

What material are you using for the hand?

```
material {
    name : "Filament Blit Material",
    shadingModel : unlit,
    colorWrite : false,
    requires: [uv0],
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = vec3(getUV0(), 0.0);
    }
}
```

 What does the model look like? 
![image](https://user-images.githubusercontent.com/1407040/83831826-c556a680-a71a-11ea-9989-b7c8f1f3ce40.png)

And on what device/OS version do you see this issue?
android 10, I use different device and os version it exits always.

**Comment by romainguy** [comment]
Thank you, we'll try to repro.

**Comment by vortice3D** [comment]
Hi there @balarayen.

I'm trying to get that same occluder-hidden behavior you're describing, but under Sceneform 1.16.0 (with Filament 1.7) I can't find the way to attach the material (matc) to a Renderable, regarding that Renderable.setMaterial seems to be broken here.

What API(s) are you using?

Thanks for your time.

**Comment by balarayen** [comment]
Hi @vortice3D 

You have to loop through the entities and primitives of a filament asset

```
int[] entities = filamentAsset.getEntities();
int instance = rm.getInstance(entities[i]);
int primCount = rm.getPrimitiveCount(instance);

```

and call `setMaterialInstanceAt()` API for the desired instance and it's primitive.

```
IEngine engine = com.google.ar.sceneform.rendering.EngineInstance.getEngine();
RenderableManager rm = engine.getRenderableManager();
rm.setMaterialInstanceAt(instance, primIndex, occluderMaterialInstance);

```


You can create `occluderMaterial` from `com.google.android.filament.Material.Builder()` by reading the filamat and then create `occluderMaterialInstance` like:

`occluderMaterialInstance = occluderMaterial.createInstance();`

Sample app in filament android code has more details on creating a material instance.

**Comment by vortice3D** [comment]
Thank you for your time @balarayen:

Using Sceneform 1.16.0 (last post-opensourcing release with Filament 1.7 dependencies) and its interface with Filament, I've finally arrived to the following code (abstract), intended to attach an occlusive-hidden material to the "CuboAlto_geo" mesh:

```
...
arFragment.setOnTapArPlaneListener(
    (HitResult hitResult, Plane plane, MotionEvent motionEvent) -> {
        if (renderable == null) {
            return;
        }

    ...

     /*----------------------------Filament interfacing---------------------------------------*/
    FilamentAsset filasset = model.getRenderableInstance().getFilamentAsset();
    Engine engine=EngineInstance.getEngine().getFilamentEngine();
    if(engine!=null){
        RenderableManager rm=myEngine.getRenderableManager();
            if(rm!=null){
                for (int entity: filasset.getEntities()) {
                    if(rm.getInstance(entity)==0){
                        continue;
                    }

                  if(filasset.getName(entity).equals("CuboAlto_geo")){
                      occluderMatInstance = occluderMaterial.createInstance();
                      rm.setMaterialInstanceAt(rm.getInstance(entity),0,occluderMatInstance);
                  }
              }
         }
    }
    ...
}
```

As you can see, this code generally reflects your views.

My doubt is about how can I construct the refered occluderMaterial Filament's material (using the com.google.android.filament.Material.Builder() as you say) in a similar way that is done with Sceneform's material:

```
Material.builder()
    .setSource(
        context,
        R.raw.background 
    )
    .build()
    .thenAccept { material->
        //do something with material
    }
```


Best regards.

**Comment by zxPhoenix** [comment]
I have the same problem with Filament 1.8 and Sceneform 1.16 for GLB model.
It was working as expected in Sceneform 1.12.
My occlusion material:
```
MaterialBuilder()
            .platform(MaterialBuilder.Platform.MOBILE)
            .name("Occlusion material")
            .shading(MaterialBuilder.Shading.UNLIT)
            .colorWrite(false)
            .depthWrite(true)
            .material("""void material(inout MaterialInputs material) {
                prepareMaterial(material);
                material.baseColor = vec4(0.0);
            }""")
```

**Comment by vortice3D** [comment]
Hi @zxPhoenix.

Take a look to [this thread](https://github.com/google/filament/issues/1994).

**Comment by verma-akash** [comment]
Hi, 
i am using Sceneform 1.16 with filament 1.7
Facing same occlusion issue with Augmented Face

The model which i am rendering is gLTF, but in Augmented Faces the occlusion material is set on a dummy renderable which is created dynamically using face mesh (uses submeshes and vertices).
So its not a gLTF renderable and cannot get fillamentAsset also to apply occluded material using filament setMaterialInstanceAt

**Comment by kayakakan** [comment]
Hi,
I think I might have a viable workaround for all this situation, regarding the usage of Sceneform with glTF. All in all, the bug seems to be the same as reported in #2423. So you can simply read that and deduce what to do, but I'm willing to give a more practical explanation on how to achieve this. However, I would point out that this is a workaround and not a fix, i.e: the bug is still present, but you shouldn't experience it again. This will simply allow you to avoid it.
I would like to speculate a bit on the issue first, but you can skip this part of the message and go right to the explanation if you care only about getting the issue resolved for you.

 - **Speculating on the issue**
After a lot of testing, I can definitely confirm that this is a Filament bug and not really a Sceneform one. The last Sceneform version that didn't display the bug was 1.12. So in order, to locate the source of the bug, I decided to reproduce the 1.12 version of Sceneform through code without calling the library. I succeeded at this, but somehow the bug was still present, and that's because I was using Filament 1.4.5. Thereafter, I checked back what version of Filament, Sceneform 1.12 was using, and I saw it was 1.3.2. So I decided to use that instead, but it didn't work! Yet, using Filament 1.3.2 through Sceneform 1.12 worked fine. I was very confused at this point, and even tried Filament 1.3.1, thinking that maybe the statement that Sceneform 1.12 was using Filament 1.3.2 was incorrect, and it was still as buggy. But then I realized that the issue might have been that Sceneform 1.12 wasn't using the Filament 1.3.2 that is released now, but one that was saved as part of the Sceneform 1.12 package. And I was correct! I simply hooked my application to use the Filament package that is part of Sceneform 1.12, and it worked just as expected. There's nothing wrong in Sceneform that would cause that bug, it's purely a Filament bug, that somehow infected earlier releases of Filament that didn't have the issue before. Which is an idea that the author of #2423 had thought about, in a back and fourth with our very helpful @romainguy. That is a bit sad that he didn't remember that issue, if he did, this thing wouldn't have been going on for so long, but that's totally forgivable, given that the issues were opened over a month apart, that would have been very surprising to remember that so clearly, especially when people start pointing at other directions, regarding the source of the issue. Despite all this, I still consider my investigation to have been worthwile, since now there's a definite proof that Filament got a very stinky bug that even went backward in releases after version 1.3.2, since we have that specific release with and without the bug.
Nonetheless, that doesn't mean that the Sceneform code is perfect. It's still has some sloppiness to it, where you have practically all the most usefull samples removed  when they could have been reimplemented quite easily.

 - **The various workarounds**
Again, you could just read issue #2423 to know what to do and it will give you an idea on what is going on, but I'll explain things in the context of Sceneform 1.16, since it's the most relevant to everyone here.
1. **Workaround 1**
This is the most simple solution, all you have to do, is to go to the `CameraStream.java` class, and change the initialization of the `CAMERA_VERTICES` member to switch the z coordinates to 0.9 instead of 1.0, which will look like this:
`private static final float[] CAMERA_VERTICES =
      new float[] {-1.0f, 1.0f, 0.9f, -1.0f, -3.0f, ..9f, 3.0f, 1.0f, 0.9f};`
However, that's not the solution that I favour. The next one is what I consider preferable.

 2. **Workaround 2**
Here, we will disable depthCulling from the camera material. For whatever reason the original material has it enabled, even though it has depthWrite disabled. Which means that it tests for depth rejection without writing to the depth-buffer anyway, which makes the test completely useless! Therefore, you shouldn't see any change in behaviour by applying this method, which is why it's what I recommend.
 2.a. **Hardcoded version**
If you go to the `sceneformsrc\sceneform\src\main\res\raw`  folder you'll see the camera material `sceneform_camera_material.matc`, all you have to do is replace that file with a material file that has depthCulling disabled. That material will look like this:
material {
    "name" : "Camera",
    "parameters" : [
        {
           "type" : "samplerExternal",
           "name" : "cameraTexture"
        }
    ],
    "requires" : [
		"position",
        "uv0"
    ],
    "vertexDomain" : "device",
    "depthWrite" : false,
    //This is the important line.
    "depthCulling" : false,
    "shadingModel" : "unlit",
    "doubleSided" : true
}
fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);

        vec4 color = texture(materialParams_cameraTexture, getUV0());
        material.baseColor.rgb = inverseTonemapSRGB(color.rgb);

    }
}
Of course this material has to be compiled with matc like this:
`matc -p mobile -a opengl -o PROJECT_PATH\sceneformsrc\sceneform\src\main\res\raw\sceneform_camera_material.matc PATH_TO_THE_MATERIAL_ABOVE.mat`
Note, that this will replace the previous material that comes with Sceneform 1.16, so not completely ideal. I would recommend the subsequent variation.
2.b. **Modifiable version**
This requires tinkering a bit more with the code to add functionality. `CameraStream.java` has a `setCameraMaterial` method that isn't accessible. So to make it accessible, you either have to have a method that returns the `CameraStream` object that's used in the session or a method that directly sets the camera material. In both cases, you have to go to the `ArSceneView.java` class, that will hold the `CameraStream` object. For example, the setter : 
`  public void setCameraMaterial(Material material){
    cameraStream.setCameraMaterial(material);
  }`
The `Material` here is a `com.google.ar.sceneform.rendering.Material` object.
3. **Workaround 3**
This is a strange one, as I don't understand why it works in the first place. Instead of disabling depthCulling in the camera material, you can instead disable it in your occluder material to get the desired behaviour. But that doesn't make any sense to me. Disabling depthCulling means disabling depth testing altogether, so there shouldn't be anything written from the occluder to the depth-buffer. Maybe it actually writes without any chance of rejection, since the test isn't performed. The only reason it would work then, is that the occluded object is drawn last, and since depthCulling should be enabled for it, it behaves as expected, but I definitely don't recommend it, as it's very clear that it would result in very bad behaviour if there is more than one occluder.
4. **Workaround 4**
This didn't work for me, but it might be an actual bug in sceneform for once. Again, all of this comes from the issue #2423, and there, it is suggested that simply setting `blending : transparent` in your occluded material will work. That was the only thing that I couldn't replicate, but maybe I did it wrong. This is also the last workaround. 

- **Some additions for the sake of completion**
@verma-akash, I too was working with augmented faces, and indeed the reliance on `*.sfb` to load materials is an issue. But you can load compiled materials instead with the `com.google.ar.sceneform.rendering.Material.builder()` method. And in the context of augmented faces you can do it in the `AugmentedFaceNode.onActivate()` method where you replace the `ModelRenderable.builder()` with code like this:
`        Material.builder()
                .setSource(context, R.raw.sceneform_face_mesh_material)
                .build()
                .thenAccept(material -> {
                    defaultFaceMeshMaterial = material;
                    updateSubmeshes();
                })
                .exceptionally(throwable -> {
                    Log.e(TAG, "Unable to load face mesh material.");
                    return null;
                });`
And you do the same with the `faceMeshOccluderMaterial` object. That's also how I load the camera material when doing the 2.b workaround.
For those who don't know, matc is a command line tool that converts material files into compiled versions. You can find it in every release of Filament, and it is recommended to use the matc tool that corrensponds to the Filament version that you are currently using. You'll find it as a donwloadable asset of a release that has the development OS that you're using in the name, like : `filament-RELEASE_DATE_IN_NUMBERS-windows`.
- **To those who use the DepthAPI**
To me, it seems that using transparent occluders is a hack, but you are forced to use it. As stated [here](https://developers.google.com/ar/develop/java/depth/developer-guide#alternative-implementation), it is much better to use shaders to occlude on a per object basis, or to simply apply depth to the whole camera texture. But there's no convenient way to turn the depth map returned by ARCore into a Filament compatible texture, and Filament doesn't seem to allow setting the z coordinate in the fragment shader. So I would like to push through to get these functionnalities, as they would complement greatly the DepthAPI of ARCore.

- **Conclusion**
Hopefully, these workarounds will help most people struggling to get Filament to play nicely with transparent occluders. 
This is my first post in the entirety of GitHub, and I hope I didn't break any rule for my first comment. That also explains why my styling is so bad, I don't really understand what's going on, but pasting the camera material, and even writting it from scratch doesn't give convincing result in the preview, and I imagine in the final version as well. It's also very rare that I would write so much English, and I hope I'm still understandable in the end. 
As a final statement, I would like to thank everyone that got involved into shedding more light into this issue, and I hope that it'll get a proper fix from the Filament team eventually. To me, this was a group effort, all the people participating in the relevent issues have my many thanks, as it helped me tremendously to find a viable solution, as I was reading through all the comments. I created my account today only to share my solution with you all!

**Comment by romainguy** [comment]
Depth testing (depthCulling in Filament) and depth writing are two different things. You can have one without the other and it's perfectly valid. The camera in Sceneform doesn't use depth writing because it's always at z=1.0 (or close to) in clip space, which means it can never occlude anything. However you want to depth test it when it's drawn last. And disabling depth testing on an occluder won't prevent it from writing in the depth buffer (but it might not do what you want then).

**Comment by kayakakan** [comment]
Thank you for your blazing fast reply. My assumptions were correct. And of course it only works because we pretty much always want the camera rendered first. But again, it would be better in the case of depth sensing  to combine the depth map and the camera texture in one go, that would ensure occlusion with any object added to the scene. I don't have that issue personally as I was working with augmented faces, but for those that do work with the DepthAPI, combining the depth map with the camera texture is the best solution.

**Comment by verma-akash** [comment]
@kayakakan Thanks for the detailed explanation of what the issue is.
1st thing i would mention is that i was already using Material.builder() in AugmentedFaceNode.onActivate(), but anyway thanks for pointing it out.
So i tried all the workarounds, and as you mentioned apart from **Workaround 4** all other workaround are working, but in **Workaround 3**, the behaviour was not perfect as in the occlusion was working perfectly but the depth writing was incorrect. 
I am using a eyeglass model and the frame part of eyeglasses around the nose was not getting occluded

**Comment by kayakakan** [comment]
Hi, @verma-akash 
I'm glad that it worked for you. 
I've already pointed out that **Workaround 3** doesn't seem very correct on principle, and as @romainguy said, depthCulling( meaning depth testing) is different than deptWrite. So I would recommend that you stick with **Workaround 2**, it's the more correct one, in my opinion.

**Comment by pixelflinger** [comment]
obsolete
