### ISSUE TITLE
Complex transparent glasses render incorrectly

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2744]
hi, I have a 'glb' glasses model exported from substance painter, which is combined with several parts of transparent submeshes. It seems the mesh sorting algorithm cannot perfectly rendering such glb models.
How can I avoid all these rendering errors in Filament 1.7.0, or is there any suggestion for making such models to reduce those rendering errors?
![image](https://user-images.githubusercontent.com/5915889/85947757-33d7fe80-b97f-11ea-8d37-fc8afdf0cc88.png)
![image](https://user-images.githubusercontent.com/5915889/85947908-1bb4af00-b980-11ea-975e-3e11520d386e.png)

Same .obj file rendered by Mac file preview:
![image](https://user-images.githubusercontent.com/5915889/85947977-a09fc880-b980-11ea-8d2e-400ccc0390f0.png)

**Comment by romainguy** [comment]
Could you share the model with us please? A solution would be enable the `twoPassesOneSide` rendering mode. See https://google.github.io/filament/Materials.md.html#materialdefinitions/materialblock/blendingandtransparency:transparency There's a screenshot showing exactly the problem you are running into.

@prideout I wonder if we should add an option in `gltfio` to be able to turn on that mode. We didn't turn it on by default because it's not what some models want. Wdyt?

Alternatively make sure the winding of all your faces is correct. What you are seeing could also be z-fighting, making sure that your triangles are not too close to each other would help.

**Comment by vcxyk** [comment]
> Could you share the model with us please? A solution would be enable the `twoPassesOneSide` rendering mode. See https://google.github.io/filament/Materials.md.html#materialdefinitions/materialblock/blendingandtransparency:transparency There's a screenshot showing exactly the problem you are running into.
> 
> @prideout I wonder if we should add an option in `gltfio` to be able to turn on that mode. We didn't turn it on by default because it's not what some models want. Wdyt?
> 
> Alternatively make sure the winding of all your faces is correct. What you are seeing could also be z-fighting, making sure that your triangles are not too close to each other would help.

hi, Thanks for you reply. Here's the model.
[test_glasses.glb.zip](https://github.com/google/filament/files/4843684/test_glasses.glb.zip)

1. The seam on the glasses seems z-fighting because it is gone when the viewpoint changes.
2. The glasses's leg behind the transparent glasses only shows the 'opaque steel' part and the 'transparent skin' part is not rendered.

**Comment by vcxyk** [comment]
append:
I tried modified the MaterialGenerator's default "blend" behavior to twoPassesDoubleSides, and the problem is gone. 
![image](https://user-images.githubusercontent.com/5915889/85982595-b52f9f80-ba18-11ea-9669-0176016df77a.png)

(ps: The default blending value is "fade" and I don't know why it's not "transparent", which is more fit for the glass specular. And It also confuses me that the depth-writing is set to 'true' explicitly for blending mode. False seems ok for my tests.).

(pps: TwoPassesOneSide solve Problem.1  above but the Problem.2 still exists.)

**Comment by romainguy** [comment]
The problem is that gltf doesn't define how blending should work. Some models expect fade, other expect transparent. I'm surprised we picked fade though. @prideout do you remember?

Setting depth writing to true for transpent objects helps with some models.

**Comment by romainguy** [comment]
What is the transparent skin you're talking about?

**Comment by romainguy** [comment]
Apparently we use fade to match other viewers, see bug https://github.com/google/filament/issues/1461

**Comment by vcxyk** [comment]
> What is the transparent skin you're talking about?

![image](https://user-images.githubusercontent.com/5915889/85984589-f5dce800-ba1b-11ea-9529-692c11e48968.png)
Look at the legs behind the glass piece.   It has a "transparent" plastic part and a 'opaque' steel inside. But through the glass we can only see the steel, and the plastic is not rendered. (Is it depth-culled by the glasses in front during the transparent rendering pass?)

**Comment by romainguy** [comment]
For that not to happen you need to make sure the sides of the frame (the "legs”) are separate objects.

**Comment by romainguy** [comment]
I finally tested your model. Some info:
- Other engines/glTF viewers exhibit the same exact artifacts when loading your .glb file
- You'll have to make the temples be separate objects for sorting/depth testing to do what you want (they are separate primitives but Filament only sorts renderables not primitives, this is something we've been wondering about doing; CC'ing @pixelflinger)
- The best results are with blending = transparent, transparencyMode = twoPassesTwoSides, like you've already discovered. See screenshot below. It sometimes leaves one last artifact (double transparency) but again that's not something that can be avoided without splitting the mesh.

<img width="1857" alt="Screen Shot 2020-06-29 at 2 25 32 PM" src="https://user-images.githubusercontent.com/869684/86057650-6bdd5100-ba14-11ea-9bb4-9352402a90d6.png">

Anyway I don't think there's anything actionable on our side aside from maybe offering a TRANSPARENT mode for glTF instead of always using FADE.

**Comment by prideout** [comment]
Note that we switched from TRANSPARENT to FADE to "fix" issue #1461.

I would rather not make this configurable since it would double the number of ubershader permutations.  It's impossible to make everybody happy when transparency in involved.  :)

**Comment by romainguy** [comment]
I know but fade is very very wrong for glass :)
