### ISSUE TITLE
When gltfio renders gltf, what parameters value are set as a default?

### ISSUE THREAD

**Issue by SGTjeong** [google/filament#2763]
**1. gltfio's default parameter's value** 

I know the bug about gltf occlusion has already been reported in #2636.

I had the same issue, so as a workaround I am applying my own material to gltf. And the result is like below.
The left one is with my custom material and the right one is with gltfio's default material.

![occlusion](https://user-images.githubusercontent.com/57657823/86204225-e8ea0100-bba1-11ea-8bae-2d0a7e0ded50.png)

Thankfully, the one with my custom material are occluded well, but it doesn't seem to have proper parameter's value(roughness, emissive, clearcoat, and something like that)

I wonder what parameters are set by gltfio as a default and the default values as well.

**2.applying videoTexture to gltf**

Since gltfio's material doesn't support videoTexture, i am using my custom material.

When I give videoTexture as a parameter to my custom materialInstance, the object turns black or red for very very short time and come back normally.

It is just like below

![blink](https://user-images.githubusercontent.com/57657823/86204974-c527ba80-bba3-11ea-8054-92241438fb45.gif)

What causes the object to blink? Any opinion would be really appreciated.

And finally, I wonder if there's no planning to add videoTexture functionality in gltfio.

Thank you!

**Comment by prideout** [comment]
(1) gltfio implements the default values that are stipulated by the glTF spec.  To learn how the standard gltfio shaders work, take a look at `ubershader.mat.in` and `UbershaderLoader.cpp` in the Filament source tree.

(2) Interesting, the flashing purple could be a synchronization issue.  I'm not sure what kind of `Stream` you're using for the video (there are 3 ways of constructing streams on Android), and when you're updating it in relation to beginFrame/endFrame, so it is difficult to diagnose this issue.  Would it be possible for you to attach a zip with a repro case?  Alternatively, tell us how to modify one of our existing samples to repro.

(3) Regarding adding video functionality to gltfio, let me think about this.  It's not a trivial feature to add, because the ubershader uses `sampler2d` for all textures; this is a fixed part of the GLSL source and cannot be changed at run time to `samplerExternal`.  We should perhaps add an `AssetLoader` feature that makes it easier for users to swap out the packaged ubershaders with custom ubershaders.

**Comment by SGTjeong** [comment]
Hi, @prideout 

Thanks for pointing out the synchronization issue, i could have fixed the flashing purple!

But I am still having issue with videoTexture's alpha.

![ezgif com-resize](https://user-images.githubusercontent.com/57657823/87004002-a8b8fd00-c1f7-11ea-8c22-f63d038950cd.gif)

I hope you could discern the transparency of jumping model above.

The point is, when i apply videoTexture, it gets a little bit of transparency, and i can't figure why.

**- How I created videoTexture**
``` 
    surfaceTexture = SurfaceTexture(0)
    surfaceTexture?.let{
                it.detachFromGLContext()
                val surface = Surface(it)
                val stream =
                    Stream.Builder()
                        .width(128)
                        .height(64)
                        .stream(it).build(EngineInstance.getEngine().filamentEngine)

                mediaPlayer?.setLooping(false)
                mediaPlayer?.start()
                mediaPlayer?.setSurface(surface)

                val engine = EngineInstance.getEngine()
                val textureSampler = Texture.Sampler.SAMPLER_EXTERNAL
                val textureInternalFormat = Texture.InternalFormat.RGB8
                videoTexture = Texture.Builder()
                    .sampler(textureSampler)
                    .format(textureInternalFormat)
                    .build(engine.filamentEngine)
                videoTexture?.setExternalStream(engine.filamentEngine, stream)
     }
```

**- TextureSampler I used ""
```
        val sampler = TextureSampler()
        sampler.setMinFilter(TextureSampler.MinFilter.LINEAR)
        sampler.setMagFilter(TextureSampler.MagFilter.LINEAR)
        sampler.setWrapModeS(TextureSampler.WrapMode.CLAMP_TO_EDGE)
        sampler.setWrapModeT(TextureSampler.WrapMode.CLAMP_TO_EDGE)
        sampler.setWrapModeR(TextureSampler.WrapMode.CLAMP_TO_EDGE)
```

I would really appreciate if you could give me any advice, thanks!

**Comment by romainguy** [comment]
Where is the transparency? It's not very clear from your GIF as it's heavily compressed.

**Comment by SGTjeong** [comment]
I explained it wrong, sorry.

I was trying to say that the color of model gets lighter than it is supposed to be

**Comment by romainguy** [comment]
Ah right, that's because Filament works in linear space. This means we expect all content to go through the sRGB EOTF (transfer function, basically a `pow(x, 2.2)` or simply `x * x` if you want to approximate it). This means that in your material you need to do something like this:

`material.baseColor.rgb *= material.baseColor.rgb;`

That should fix your issue.

**Comment by SGTjeong** [comment]
You saved my day, @romainguy .

Thank you so much.
