### ISSUE TITLE
Volume rendering support

### ISSUE THREAD

**Issue by feliwir** [google/filament#278]
Hello everyone,

i am interested in rendering medical volume images using filament. It's very useful to combine augmented reality with medical data like e.g. CT images. Since i am working in medical computer science i'd be happy to contribute to this idea.

**Describe the solution you'd like**
Implement a simple single pass volume renderer and add the possibility to pass 3D image in memory. Add support for common things like transfer functions and scale bias/level window.

**Describe alternatives you've considered**
I've rendered volumes in OpenGL before with good visual appearance, but the augmented reality aspect was missing. Alternativly there also exists the VTK framework, which is very bloated though. It doesn't have any AR functionality i know of.

**OS and backend**
Not OS specific.

**Comment by prideout** [comment]
I've worked on volume renderers, they are cool but Filament's core strength is surface rendering, with physically-based lighting and materials. This is probably out of scope for the library.

Also note that Filament does not have AR functionality, we are lower level than that.

**Comment by romainguy** [comment]
What is required for volume rendering exactly btw? Can this be done with custom materials and 3D textures?

**Comment by prideout** [comment]
Yes a volume rendering API could either be (1) "give us a 3D texture we'll ray march it for you...oh and give us coords for a cuboid that the texture maps into, so that we can honor the camera correctly" or it could be (2) "give us some surfaces and desired voxel resolution, we'll voxelize them for you".

If we do the ray marching in filament we'd probably want to let clients configure the march size and the step size for ray marching

We could also do [fake volume rendering](http://prideout.net/blog/?p=51) by rendering signed depth into a floating point buffer with additive blending.

**Comment by romainguy** [comment]
My point was that ray marching could be done in a custom material right? It sounds like all we need is support for 3D textures (which would be useful for other features anyway).

**Comment by prideout** [comment]
Yep, if we merely supported 3D textures, the client could set up a screen-aligned quad and do all the hard work on their end.  We could claim that "we support volume rendering" and it would technically be true :)
