### ISSUE TITLE
Scene is suddenly much lighter when going from 1.7 to 1.8.1

### ISSUE THREAD

**Issue by rawnsley** [google/filament#2917]
I guess this is due to the [ColorGrading improvements](https://github.com/google/filament/pull/2613). A couple of questions:

1. Why isn't the default "no color grading"?
2. Are there any performance implications to having color grading active? I'm on a mobile platform with a tight budget.

My understanding of color grading is very limited so apologies if these questions don't make sense.

**Comment by romainguy** [comment]
There is no color grading by default. There is however always tone mapping like before, but it's applied via the color grading LUT. Using advanced color grading features is therefore free now since we always use that LUT. We changed the default tone mapper between 1.7 and 1.8 but they should be pretty close. You can switch back to the old tone mapper by choosing the one called "Filmic".
