### ISSUE TITLE
ModelExporter or MaterialEditor for filament?

### ISSUE THREAD

**Issue by vcxyk** [google/filament#2941]
Filament supports a lot of features including clearcoat, sheen, transmission, etc;  but I cannot find a filament exporter for 3ds max/blender/maya and the standard gltf format can only support a subset of filament's rendering features...  while programmers can manually edit the material params to make those features work, artists are not able to produce lots of models in this way.  
Is there some best practice to make Filament's model for artists?  Or any WYSIWYG filament exporter in schedule?

**Comment by romainguy** [comment]
This is something we'd like to do but it's not a priority at the moment unfortunately. glTF is catching up to our capabilities:
- clear coat
- transmission (refraction)
- volume transmission
- sheen (cloth)

The gltf exporter built with Blender has been adopting new features too. Clear coat works for instance.

The main reason it's not a priority is because filament does not define file format on purpose.

**Comment by roxlu** [comment]
I've been working on SimpleScene, which is an exporter for Blender and XML format, that tries to follow the specs/features of Filament as much as possible. Currently this is for an internal project as I don't have the resources to support an open source project. But if more people would benefit from something like this I'm happy to put this on Github. Please leave a thumbs up if you would like this.

I'm following a somewhat similar approach to GLTF and some other internal formats I've worked with. Instead of using JSON I use XML. I think both formats are valid, but I find XML more readable. Assets like meshes and textures are stored separately and the XML has references to these files. I try to keep the XML as flat as possible and I only store one scene per file. 
A separate tool which parses this XML and compiles the materials, generates the ktx files, filamesh files etc. 

I've pasted an example of the XML here https://gist.github.com/roxlu/dc6286b6cab70546e12f0e01097556d7 which generates a scene similar to this:

![image](https://user-images.githubusercontent.com/358809/89989120-c78c3280-dc80-11ea-971c-0b4c5e26b6ce.png)

Some screenshots of the exporter:

_output settings_
![image](https://user-images.githubusercontent.com/358809/89989223-f30f1d00-dc80-11ea-90ec-3ac268ce2da9.png)

_view layer settings_
![image](https://user-images.githubusercontent.com/358809/89989327-15089f80-dc81-11ea-823e-61ede98992ff.png)

_world settings_
![image](https://user-images.githubusercontent.com/358809/89989358-205bcb00-dc81-11ea-8dac-3aa25cad889c.png)

_render settings_
![image](https://user-images.githubusercontent.com/358809/89989395-310c4100-dc81-11ea-9bf9-9e70a3d77df2.png)

_object settings_
![image](https://user-images.githubusercontent.com/358809/89989432-3d909980-dc81-11ea-9a1b-4ad76f7ad744.png)

_material settings_
![image](https://user-images.githubusercontent.com/358809/89989475-4aad8880-dc81-11ea-9033-a8f3a0280ded.png)

_sun light settings_
![image](https://user-images.githubusercontent.com/358809/89989539-5c8f2b80-dc81-11ea-8c15-50fb3fe3fb09.png)

**Comment by pixelflinger** [comment]
very unlikely we can work on this any time soon
