### ISSUE TITLE
Refractive material and DOF with 2+ anti-alias samples crash in Metal

### ISSUE THREAD

**Issue by ast3rX** [google/filament#2984]
**Describe the bug**
Transparent shader with screen-space refraction and depth of field with 2+ anti-alias samples crash the engine when using the Metal backend.

```
Error message: Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)
validateAttachmentOnDevice:490: failed assertion `Memoryless attachment cannot be loaded as it have no memory to load from.'
```

Tested with hello-pbr from the samples.
Tested with filament 1.8.0 and 1.8.1.

**To Reproduce**
1. Use a transparent shader with screen-space refractions on the subject model. Both solid and thin types produce the bug.
2. Turn on depth of field effect. (default parameters)
3. Set viewSamples to or higher than 2.

**Expected behavior**
Rendering without crash.

**Smartphone:**
 - Device: iPad Pro 12.9" 2018
 - OS: iOS 13.6

**Comment by bejado** [comment]
@pixelflinger 

This is happening because the Metal backend attempts to do our "magic resolve" for the depth buffer, which should never happen (averaging depth samples is incoherent).

What we should be doing is preserving the full MSAA depth texture from "Color Pass (opaque)" and waiting until after the transparent pass to resolve.
