### ISSUE TITLE
Overlay view sharing depth data with the main one

### ISSUE THREAD

**Issue by jeanlemotan** [google/filament#3145]
Is there any way to render a vew on top of another one while still using the depth buffer generated by the first one?
The use case is this: I render a view containing my main scene and I want to overlay some debug helpers (wireframe graphics) for lights and selected object in a secondary view. However, right now the secondary view cannot share the depth buffer with the first one - or I could not find a way to do so - and my wireframe helpers don't get occluded properly.

The reason for doing it like this and not rendering the wireframe things in the main view is because I don't want them processed by the post effect.

Thanks

**Comment by romainguy** [comment]
You should be able to do this by disabling the depth clear. @pixelflinger can give you more details.

Note however that you don't need a second view necessarily. If the camera is the same, you can simply use layer masks to hide/show a bunch of objects easily. We do this in our (terrible) sample apps. If you look inside libs/filamentapp, you'll see we use layers/layer masks to show/hide debug renderables.

**Comment by pixelflinger** [comment]
Actually there is no way to do this at this time. A new depth buffer is allocated for each view.

There is one special case where you can probably achieve this: if you disable post-processing for all views, then the depth buffer can probably be shared between the views.

**Comment by jeanleflambeur** [comment]
Is there any strong reason not to expose the depth buffer of the view so that it can be shared with other views?
I guess that internall all rendering is done in a HDR render target with a depth attachment and the post effects are used to 'resolve' this into the actual view render target that doesn't have nor need a depth buffer, right?
The initial depth buffer is still very useful for several techniques - like mixing a 2D UI view with the 3D scene while taking the depth into account to do some occlusion.

**Comment by pixelflinger** [comment]
1. Currently, views are very separate from each other, there is no state maintained between calls to render().

2. We generally discard the depth buffer to save bandwidth. In order to share it with future calls to render(), we would need special apis to keep it around.

3. Views can also have different sizes, positions and scaling options, which all affect the depth buffer.

So as your can see, there are many problems to solve before we can allow this.

**Comment by jeanleflambeur** [comment]
I understand, if depth were to be shared it would need to be stored instead of discarded. I assume that for some post effects - like depth of field or SSAO you do store the depth buffer.
Sharing would also work only if the resolution is compatible - and I think there are other constraints, in OpenGL ES at least where only come combinations of buffer formats are compatible, even if each individually is renderable and needs to be checked with glCheckFramebufferStatus.

Right now it is possible to attach arbitrary attachments to a render target the same caveat applies - the need to be the same size, etc.

I think that exposing an api to configure the store operation (Discard or Store) for the depth buffer and exposing the depth texture in the view would allow depth sharing between views. Of course, I'm saying this without knowing the filament implementation details.
