### ISSUE TITLE
How to get the hacked bistro test scene in gltf formate?

### ISSUE THREAD

**Issue by Superlee506** [google/filament#3248]
The bistro scene rendered with Filament’s glTF viewer looks amazing,  where can I find the bistro scene?

Thanks.

**Comment by romainguy** [comment]
It's the scene from https://developer.nvidia.com/orca/amazon-lumberyard-bistro opened in Blender and exported as glTF. We simply added light sources and emissive properties to various surfaces, that's about it (you may need to fix the blending of the foliage, I believe it's opaque instead of alpha masked). I don't know what the license would be to redistribute our version though (also, it's very large).

**Comment by Superlee506** [comment]
@romainguy 
Thanks romain guy. 
The ORCA dataset is under  license  of "CC-BY 4.0". You are free to share and adapt.  
If it's convenient, could you share it with me? I really love the rendered image.
