### ISSUE TITLE
Web API reference incomplete?

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3250]
the javascript API reference is here https://google.github.io/filament/webgl/reference.html
but it seems to be incredibly incomplete, for instance it does not have scene.addEntity or really much of anything, if you look at the filament.d.ts file it declares much more than is present in that reference page, is there a more complete version available?

**Comment by prideout** [comment]
Yes it needs to be fleshed out, the typescript bindings are more up-to-date.  The most authoritative source is `jsbindings.cpp` and our C++ headers.

**Comment by davidwarford** [comment]
Okay. So for the time being I should read the c++ headers then?

**Comment by prideout** [comment]
Yes the C++ headers and the demos in `web/samples` are your best bet.

I think we should probably simplify our JavaScript documentation process.  Currently we use a custom python script to slurp up scattered comments.  Instead, we should simply consolidate all the documentation into the TypeScript definitions file, so that it's one place.

**Comment by davidwarford** [comment]
Yes if the typescript definition file had comments that would have been ideal for me.

**Comment by prideout** [comment]
I added some notes to #5530 yesterday, in a sense this a dup of that bug, closing.
