### ISSUE TITLE
Engine.create() undefined.

### ISSUE THREAD

**Issue by davidwarford** [google/filament#3294]
This issue is a question and (probably) not a bug. I decided i would try and learn from the [hexgl ](https://github.com/prideout/hexgl) project made by @prideout to try and learn how to properly setup filament with typescript (as it has been a struggle for weeks now). so I updated filament in the project did `yarn build` and started my webserver, however when I load the web page it fails on `Filament.Engine.create()` the error being `Uncaught (in promise) TypeError: Cannot read property 'create' of undefined`. I decided to put a break point on the line that `Filament.Engine.create()` is defined and it does get called before the error is thrown. I know the project is old and was built for a older version of the API so I decided to start fresh but I get the same error. What am I doing wrong?

**Comment by davidwarford** [comment]
#2913 Interesting, does filament no longer work with webpack?

**Comment by prideout** [comment]
For one of the emscripten upgrades that we did, we had to update the way the wasm loading & initialization works, so yes the webpack configuration in my old hexgl demo no longer works with newer versions of Filament.

Using webpack is complicated here because of the unusual setup involving a wasm file and a JavaScript file that loads it and provides a glue layer.

To get started, I suggest a simple setup similar to what we do in `web/samples/*.html`, then later migrating to webpack or rollup or whatever your favorite webdev tools are.

**Comment by davidwarford** [comment]
my issue is I really want to be able to use type script. thanks for getting back to me though

**Comment by prideout** [comment]
Understood.  FWIW, we know of one user of the TypeScript bindings, and they use rollup rather than webpack:

https://github.com/google/model-viewer/tree/master/packages/render-fidelity-tools

**Comment by davidwarford** [comment]
Thank you. really grateful for your help. sorry for all the pesky issues.
