### ISSUE TITLE
Render transparent and emissive gltf model incorrectly

### ISSUE THREAD

**Issue by Miao-10k** [google/filament#3454]
I was using this [gltf model](https://sketchfab.com/3d-models/paladins-book-ancient-knights-secrets-07bc6364101c4bd4adaa3d0cee1aaa3e).
It was expected to look like the preview provided on Sketchfab.
![image](https://user-images.githubusercontent.com/32147896/105815660-3de1de80-5fee-11eb-870a-6a64a894c0b0.png)

But when I use the Modelviewer class to load and view it on an Android Device,  it looks incorrectly rendered as following. It seems that the alpha map was ignored when rendering emissive.
![image](https://user-images.githubusercontent.com/32147896/105815619-2efb2c00-5fee-11eb-93bb-fe094377eac6.png)

Besides, when the transparent part overlays with other parts, it looks wrong from some angle. I've gone through issue #2744, but I haven't figured out how to set the transparency mode to twoPassesTwoSides in java when using gltf model.
![image](https://user-images.githubusercontent.com/32147896/105829245-0fb8ca80-5fff-11eb-9dfb-18b48b69852e.png)

**Comment by romainguy** [comment]
The glTF specification unfortunately does not say anything about how emissive should be applied. It will give the result you want if you use alpha masking instead of alpha blending. It would kind of make sense to apply the alpha factor to emissive although I can imagine arguments against that. I'll fix it.

**Comment by romainguy** [comment]
There might also be a problem with the glTF conversion from Sketchfab as this glTF doesn't open in all other glTF viewers I've tried. It loads in Blender but with similar backface/transparent issues. The emissive behavior in Blender is the one you expect though.

**Comment by romainguy** [comment]
The problem with the pages making each other invisible is that they're all blended and cannot be sorted properly. The non-transparent ones should use alpha masking instead to solve this problem.

**Comment by Miao-10k** [comment]
Hi @romainguy,
Thanks for your reply. Just one more question, what about the occlusion that occurs at some angle when transparent planes overlap? The alpha values between 0 and 1 will be dropped if using alpha masking.


![image](https://user-images.githubusercontent.com/32147896/105984325-e5394100-60d4-11eb-9458-d9b98e1a4e24.png)

![image](https://user-images.githubusercontent.com/32147896/105984356-f08c6c80-60d4-11eb-88ba-e16fef9ecc61.png)

**Comment by romainguy** [comment]
This happens because we write transparent objects to the depth buffer to help with certain glTF files. This is something we've gone back and forth on and there's no great solution here. Overlapping transparents are always a problem unfortunately.

@prideout might remember specific details about why we write transparents to the depth buffer (which is not a problem when they don't overlap thanks to the sorting).
