### ISSUE TITLE
Lighting and negative scales

### ISSUE THREAD

**Issue by cjsliuj** [google/filament#3635]
**z-axis zoom -1**
![z-1](https://user-images.githubusercontent.com/4098790/110756382-159ffd80-8285-11eb-8d6b-316fa4820085.png)
**rotated by 180 degrees around the y-axis**
![y180](https://user-images.githubusercontent.com/4098790/110756412-1df83880-8285-11eb-883a-8cb91bd035a1.png)

**Comment by prideout** [comment]
Can you add more details to your question?  Is this about the orbit-style camera manipulator?

**Comment by romainguy** [comment]
@prideout Don't we have an API to enable normals flipping when a negative scale is applied?

**Comment by prideout** [comment]
Ah right, I was confused by the issue title.  To conform to the glTF specification, Filament automatically flips the face winding when the determinant of the transform matrix is negative.  This is useful when creating symmetrical models because you need to specify only half of the geometry.  

This is a fairly standard feature so I would be surprised if we're deviating from other popular renderers.

@cjsliuj if this is a problem for you that does not exist in other glTF viewers (e.g. [this one](https://gltf-viewer.donmccurdy.com/)) then maybe you could attach an example model as a zip file.

**Comment by prideout** [comment]
Some links for more background on this feature:

https://github.com/google/filament/issues/1520
https://github.com/google/filament/issues/3001
https://github.com/KhronosGroup/glTF-Sample-Models/issues/273
https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Node_NegativeScale

**Comment by cjsliuj** [comment]
I found change like this will fix the problem（Is this change appropriate?）:
**original**
<img width="748" alt="企业微信截图_d95eb6c0-b694-4c50-a86e-8e63bd92f68f" src="https://user-images.githubusercontent.com/4098790/110833869-db138080-82d7-11eb-9a1a-018f96ffbead.png">
**after changed**
<img width="822" alt="企业微信截图_b8587230-c84c-4951-a758-09df14acc0d0" src="https://user-images.githubusercontent.com/4098790/110833878-dcdd4400-82d7-11eb-9773-8f7f7f8fd199.png">

**Comment by prideout** [comment]
We intentionally use a cofactor matrix as described here:
https://github.com/graphitemaster/normals_revisited

**Comment by cjsliuj** [comment]
Thanks
