### ISSUE TITLE
TransformManager missing setWorldTransform function

### ISSUE THREAD

**Issue by paulorrfilho** [google/filament#3665]
Tranformanager has both get and set local transform functions however, there is only a get function for the world transform.
Am I missing something?

**Comment by romainguy** [comment]
The world transform getter returns the local transform composed with the parent's transform all the way to the root. It's a computed value and that's why there's no setter. The local transform you set is the model to world transform of the tntithu relative to its parent. If you have no parent then both getters return the same thing.
