### ISSUE TITLE
Documentation for framegraphs or building alternitave renderers?

### ISSUE THREAD

**Issue by warvstar** [google/filament#3672]
Is there any documentation available? I'm interested in using Filament as a starting point for my next game engine, one of the things I'm interested in is the ability to have different renderers (forward,deferred,raytraced) and to build framegraphs / rendergraphs using a node system. I'm also interested in adding optional compute and raytracing passes and a WebGPU backend.

I've currently looked at these two alternatives as starting points but they each have their drawbacks and neither look as organized or as actively worked on as Filament.

https://github.com/NVIDIAGameWorks/Falcor
https://github.com/ConfettiFX/The-Forge

Is there any reason I should not use Filament as a starting point for my project? Thanks

**Comment by romainguy** [comment]
All the documentation available about the internals can be found in the comments in the source code. The frame graph will eventually become a public API, at which point we'll provide more extensive documentation.

WebGPU and compute are also features we plan on adding. Compute will be a bit complicated because we must target OpenGL ES 3.0 which doesn't have compute capabilities. That said it will probably be achieved by creating a new material domain `compute`, like we did for post-processing.
