### ISSUE TITLE
Documentation errors with color in LightManager.h

### ISSUE THREAD

**Issue by jwwalker** [google/filament#3841]
The header documentation for `LightManager::Builder::color`, `LightManager::setColor`, and `LightManager::getColor` refer to a "linear sRGB color-space".  It's my understanding that linear and sRGB are alternatives, so "linear sRGB" doesn't make much sense.  Perhaps "linear RGB" was intended.

**Comment by romainguy** [comment]
No, that's correct. "Linear RGB" does not explain what the color space is. "Linear sRGB" means an RGB color defined in the sRGB gamut (sRGB white point + chromaticity) but without the EOTF applied ("gamma").

**Comment by jwwalker** [comment]
Huh.  I did try Googling "linear sRGB" and didn't find anything like that, just linear OR sRGB or converting between linear and sRGB.

**Comment by romainguy** [comment]
The term "linear" by itself is often abused to mean "linear sRGB" (or at least a color in the sRGB gamut without a transfer function applied to it). It unfortunately creates a lot of confusion and that's why Filament tries to be very precise whenever we discuss colors. You will notice for instance that we avoid the term "gamma" and instead use EOTF and OETF (electro-optical and opto-electrical transfer functions) which are more accurate terms.

**Comment by romainguy** [comment]
BTW in case it helps I wrote good documentation for various common color spaces (including sRGB and linear sRGB) here: https://developer.android.com/reference/android/graphics/ColorSpace.Named. The linear color spaces all have a linear transfer function.
