### ISSUE TITLE
Integrating FilamentApp into existing window/app.

### ISSUE THREAD

**Issue by ScatteredRay** [google/filament#3937]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate Filament into another application and would like to integrate with my own windowing/input/main loop.

It seems a lot of the libraries are fairly well build to do this, and doing this modularly shouldn't be too hard by duplicating a bunch of code in FilamentApp. But for an application that doesn't concern itself much with the actual rendering, it seems that there is a lot in FilamentApp that it'd be nice to abstract and re-use.

**Describe the solution you'd like**
Splitting FilamentApp out into the portions that care about input/presentation/looping, and are currently using SDL, and the portions that care more about bringing up filament, with a scene with navigation I think would help integration into various applications that just really need some basic (and good looking) rendering.

**Comment by romainguy** [comment]
`FilamentApp` is part of our samples and really not production-quality code. Filament aims to only be a renderer and nothing more (except accompanying libraries like gltfio to load glTF files, etc.). What `FilamentApp` does for input for instance is quite specific to our samples, but that's why we provide instead the `camutils` library which implements camera controls for you (you are still responsible for handling inputs in the way that's best suited for your app though: SDL, GLFW, etc.).

If you'd like code that's easy to use to display models, etc. I would highly recommend you use the `gltfio` and `viewer` libraries. The format is a glTF loader (which will give you animations, scenes, etc.) and the latter provides a ready-to-use Filament setup to display glTF scenes. It is used by our gltf-viewer sample for instance.
