### ISSUE TITLE
WebGL docs should be included in archives

### ISSUE THREAD

**Issue by romainguy** [google/filament#394]
The docs generated in `docs/webgl` should be included in the web archive produced by `build.sh`.

**Comment by prideout** [comment]
I'll give it a shot, should be possible. Users can't simply open the HTML tutorials from their local filesystem due to CORS restrictions, however our docgen script has a `--disable-demo` option that we would use for the bundled tutorials.

I did an experiment to confirm that the Kokoro machines we use for the webgl builds already have Python 3 on them, which is what our docgen script uses.
