### ISSUE TITLE
Possible performance issue with fragment shaders and overdrawn geometry

### ISSUE THREAD

**Issue by teub** [google/filament#4015]
**Describe the bug**
I noticed a significant performance hit that seems to depend on the resolution, for opaque geometry that is overdrawn and for which I didn't expect the fragment shader to run. I suspect there's more to it but I'm not sure what.

I'm not sure how to investigate this properly, but here's how I made a simple test case:

- I made a sphere.obj with 4k triangles, then another sphere_dedup.obj where all the triangles are duplicated N times (until I get about 1 million triangles, so ~250x times the original sphere).
- I removed all the mesh optimizations from MeshAssimp::setFromFile
- I added some timing code in material_sandbox.cpp, commented out SDL_Delay(16) in FilamentApp.cpp, and added a flushAndWait after the rendering.

The results I get on a 1080ti are: 
- sphere.obj renders in 1.5ms, 10ms when the window is maximized (maybe that's ok)
- sphere_dedup.obj renders in 6.3ms, 46ms when maximized

Doesn't it sound too much ?
In the first case, I understand the fragment shader has more fragments to compute when the window is maximized; I guess that there are also a lot of work to do that don't depend on the geometry I'm pushing.
In the second case, I don't get where the additional 30ms come from, assuming most fragments should be discarded.

~~Could there be an issue with zwrite and depthCulling not working as intended or~~ was I just being too optimistic with my GPU?
Edit: actually, this zwrite/depthCulling wouldn't save the lighting computation by themselves, I guess this would/should be taken care of by an unlit z-pass but I don't know.
Edit2: or maybe it would? the zpass could save the lighting of invisible faces, but isn't the depthCulling supposed to avoid reshading the same triangle again and again?

Note that my real case was me trying to duplicate skinned geometry to workaround the fact that there's no instancing available, but this test case seems to capture the essence of it. I could also be completely wrong and maybe this is normal for this many triangles.

**To Reproduce**
I attached the 2 obj to this ticket, plus a patch of the quick changes I made to have some sort of performance measurement (displays the average render time in seconds every 100 frames). Note that the GetTime code I used is for windows.

[spheres_and_profile_patch.zip](https://github.com/google/filament/files/6528960/spheres_and_profile_patch.zip)

**Expected behavior**
I expected both render time to be cheap as in theory the sphere_dedup.obj doesn't need more lighting computations than sphere.obj.

**Desktop (please complete the following information):**
 - OS: Windows
 - GPU: NVIDIA GTX 1080
 - Backend: OpenGL

**Comment by romainguy** [comment]
You are most likely suffering from additional quad shading here. We used to have a depth prepass to combat this but it was causing a lot of compatibility issues on various GPUs and sometimes performance was worse because of the extra draw calls.

I don't think this test is representative of what would happen if you duplicated skin geometry.

**Comment by pixelflinger** [comment]
So... In theory the fragment shader shouldn't run each time, but we should make sure we set the depth buffer test so that equal depths are discarded. I think we're doing this right, but it's worth double checking. I will do that on Monday.

Second point, you may just be overwhelming the vertex stage and/or the rasterization stage. But that theory might not hold because performance degrades significantly with the resolution.

Could you try to create sphere debug so that ask the extra triangles are inside the sphere (by using a smaller radius), this should guarantee that these triangles won't be shaded.

You could also try this year with an unlit, trivial, shader.

**Comment by teub** [comment]
Well as I had no way of controlling the number of instances, some were overdrawing themselves, and the framerate was tanking when getting close to those ones. I'm just moving them out of the view now but I thought this could be the symptom of some other problem. 

So without a depth pre-pass, your render time depends on how lucky you are with the order of the primitives, right? I guess you can sort entities at a higher level to minimize the overdraw, I don't know. On my scenes I'm struggling a bit to keep at 60fps on my 1080, already had to give up MSAA.

@pixelflinger : this definitely looks like equal depth fragments are re-shadowed; I'm not sure I want to create 250 new spheres to test that :)

**Comment by romainguy** [comment]
If you give them proper bounding boxes the front to back sorting + depth buffer should eliminate most of the overdraw. It won't however fix overshading due to quad shading, we still need to add support for LODs to solve this (or bring back a more robust depth prepass). But yes, within a single model the order in which the primitives get processed by the GPU will impact the result (at least for primitives that don't get backface culled).

**Comment by teub** [comment]
I'm out of luck then because the bounding box of my fake-instanced geometry is very big :)

**Comment by romainguy** [comment]
Can it be smaller? :)

**Comment by teub** [comment]
Not really, I'm using a single entity to display n characters at various locations, which was the point of instancing. Note that for something like trees or vegetation, this would be the same issue.

**Comment by romainguy** [comment]
Does it have to be a single entity? You will definitely lose out on the sorting and culling we perform in engine.

**Comment by teub** [comment]
I actually have more than 1 entity, but their instances need to be far apart for you not to see them being repeated.
The more spread out they are, the less you see it; so yeah, it implies big bounding boxes.

I guess one day there will be true instancing in filament and maybe the depth pre-pass will be back, so I'm not worried :) I hope these use cases help you evaluate what could be useful.

**Comment by romainguy** [comment]
I still don't get why you can't have 1 entity per instance (or at least per few instances). Multiple entities can share the same vertex and index buffers. The "only" added cost will be the per entity UBO but those are small (they only contain the transform matrix).

**Comment by teub** [comment]
> I still don't get why you can't have 1 entity per instance

10000 animated characters is currently a big no-no. setBones is already costly (I've seen it mentioned in another ticket), there's no way I can call this 10k times.

Maybe I should consider sharing the vbos but it's currently not the bottleneck, and not doing it will help me create more visual variety.

**Comment by pixelflinger** [comment]
Currently, to simulate instancing, you need to create N renderables, each using the same vertex/index data, which will allow you to have a tight bounding box.

Using large bounding boxes with a lot of empty space in them, will hurt filaments culling and sorting significantly.

**Comment by teub** [comment]
@pixelflinger I can't create 1 renderable per animated character for that many characters: as mentioned above, setting their pose individually would be too costly. I'll keep this in mind though, maybe it can be useful for other things.
I knew big BBs would come with compromises, I already disabled shadows on them; I didn't expect the overdraw problem though.

**Comment by pixelflinger** [comment]
Why would it be too costly? And how many are we talking about?

**Comment by teub** [comment]
> Why would it be too costly? 

It's computing quats out of matrices each time you call setBones, when I only want to do it once for the few different poses I compute.

> And how many are we talking about?

A very large crowd; my initial need was 10k people, I'm already quite below that :)

**Comment by pixelflinger** [comment]
Note that there is a version of `setBones()` that takes quarternions directly. You could use that to avoid the matrix to quat conversion.

Honestly, I would try this, rather than messing with the bounding boxes. 

There are definitely many things we can improve for your use case, and I'll look into it, but given the current situation, the best approach would be one renderable per instance, tight bounding boxes and the version of setBones that takes an array of `Bone`.
