### ISSUE TITLE
How to get the TextureID that after Filament rendering?

### ISSUE THREAD

**Issue by RockVampire** [google/filament#4270]
Now I'm trying to use filament to render something in the video living room on mobile platform. I have tried to push the video stream into filament by Stream and ExternalTexture like what was done in the stream-test-sample. 
But the interface I'm using request a textureId to push the video stream to the server.
Can I get the texture id after filament rendering ,or how can I get the "output data" instead of drawing them on the UI.

**Comment by RockVampire** [comment]
Is There any example render on a surfaceTexture?

**Comment by romainguy** [comment]
Please use a discussion instead of a bug report for questions. You can render with Filament into any `Surface` by creating a `SwapChain` around that `Surface`:

```
swapChain = engine.createSwapChain(surface)
```

See the source of [UiHelper](https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java) for a complete example of how to create that `SwapChain` (in particular, `attachTo(@NonNull TextureView view)`).
