### ISSUE TITLE
Filament Android samples - FPS measurements

### ISSUE THREAD

**Issue by sarathsi** [google/filament#433]
I have built and able to run the filament android samples. It would be useful to see the FPS / rendering performance of the samples.

Solution Idea: I think android.os.SystemClock.elapsedRealtime() api may be used once per frame and get the frame timings.

**Comment by romainguy** [comment]
FPS is not a really useful measure, we prefer frame times. That clock is also not super useful since it doesn't include the GPU time, you'd be mostly measuring vsync and frame skips. We use fences internally to track performance (it's how dynamic resolution works). Anyway, I'd rather rely on systrace for performance rather than on screen counters.
