### ISSUE TITLE
Can't be showed at behind a object with a transparent or fade blending material

### ISSUE THREAD

**Issue by fanbinnet** [google/filament#4505]
Draw an object which with material the params blending be seted to fade or transparent.
Then draw another object with the same material. The first object can't be displayed.
Below is the screencapture:
![issue1](https://user-images.githubusercontent.com/3060688/129554380-072c6f06-9432-41b3-a616-adf3c495b810.JPG)

![issue1](https://user-images.githubusercontent.com/3060688/129554395-32646acc-07ef-4adf-9ef1-250bdfc9b721.JPG)

The model can download from the below url:
https://github.com/google/filament/discussions/4010

**Comment by romainguy** [comment]
This happens because these objects use transmission (screen space refraction), which works by copying the color buffer. Only one such layer is allowed, which is why the result is what you see above. This is a common limitation as it would otherwise require an expensive resolve + copy for each object drawn.

**Comment by fanbinnet** [comment]
@romainguy in my work scene, we don't use transmission, we just use transparent  blending ,
there is the same issue.

**Comment by romainguy** [comment]
Transparent blending works fine in all the tests assets we use. Please provide an asset showing the problem.

**Comment by fanbinnet** [comment]
OK,I retest use the asset in #4010, it can work fine.
I will analyse if I have make some mistake in my work scene.
