### ISSUE TITLE
glTF conformance: transmission roughness

### ISSUE THREAD

**Issue by elalish** [google/filament#4578]
It seems Filament is making the roughness artificially high on models with small transmission roughness values: https://modelviewer.dev/fidelity/#khronos-IridescentDishWithOlives

**Comment by romainguy** [comment]
So that one's complicated. All the renderers are wrong, and in Filament we use an empirical scale factor to match cubemap and screenspace refraction (basically at infinity). There was a long discussion between @pixelflinger and I on the glTF Slack. We need the spec to be better defined here (other renderer under-estimate the roughness). Removing the empirical factor brings Filament closer to reference path tracing (which will be more blurry than three/babylon).

**Comment by elalish** [comment]
Ah, interesting! Sounds like a good discussion for the PBR Next call; anyone available at 9am on Mondays? Anyway, once dspbr-pt puts out a new release I can put in a ground truth to aid the discussion.

**Comment by romainguy** [comment]
Yes, @pixelflinger and I can join a discussion on Mondays at 9am.

**Comment by romainguy** [comment]
Closing this for now with the removal of the scale factor. This will need more investigation with the working group.
