### ISSUE TITLE
MosquitoInAmber: "roughness" seems to be to "rough"

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#4656]
**Describe the bug**
[MosquitoInAmber](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MosquitoInAmber) sample model is rendered quite differently in Filament (via [Web viewer](https://google.github.io/filament/viewer/)) if compared to https://gltf-viewer.donmccurdy.com/ and https://github.khronos.org/glTF-Sample-Viewer-Release/ 

It seems that if to scale down `roughnessFactor` on the rock material from 0.5 to 0.37-ish, it starts to be more similar.

Was that the intended behavior?

**Comment by romainguy** [comment]
It is and it is not. We are currently discussing this issue with Khronos because unfortunately the other viewers are also wrong, but at infinity. Long story short: the blurriness should depend on how far objects behind the transmissive object are, and Filament picked being correct at infinity. This will change once the glTF group can agree on what a good compromise would be.
