### ISSUE TITLE
Rendering order difference when upgrading to latest

### ISSUE THREAD

**Issue by MarkMurillo** [google/filament#4700]
Hi there!

Originally I was working off this version:
```
implementation 'com.google.android.filament:filament-android:1.9.4'
implementation 'com.google.android.filament:filament-utils-android:1.9.4'
implementation 'com.google.android.filament:gltfio-android:1.9.4'
```
And upgraded to
```
implementation 'com.google.android.filament:filament-android:1.12.7'
implementation 'com.google.android.filament:filament-utils-android:1.12.7'
implementation 'com.google.android.filament:gltfio-android:1.12.7'
```

Where I noticed a bug when trying to render a flat texture of a camera stream coming from ARCore, then rendering models, planes on top of it. In the previous version, I would just add the flat renderable that contained the camera stream to the scene, then add other entities (plane/model renderables) after that and it would draw the plane/model renderables on top of the flat camera renderable no problem:

<img width="341" alt="Screen Shot 2021-10-05 at 10 38 05 AM" src="https://user-images.githubusercontent.com/3269726/136045816-51356055-2cec-44db-a93c-b4e9f4beb915.png">

However, after upgrading to the latest release, all I saw now was just the flat camera texture and none of the other renderables that are added afterwards:

<img width="338" alt="Screen Shot 2021-10-05 at 10 41 55 AM" src="https://user-images.githubusercontent.com/3269726/136045971-9a81f601-5e68-453b-b038-6738930ded06.png">

I wondered if I disabled the flat camera renderable if I would see the other renderables, and it turned out this was true:

<img width="337" alt="Screen Shot 2021-10-05 at 10 42 08 AM" src="https://user-images.githubusercontent.com/3269726/136046650-3f7408a7-7fdd-4ec1-a4b0-95dbd2a7c0fa.png">

Notice there is also an artifact at the bottom left corner of the scene which seems to change into random colors which I can't seem to explain...

I've also tried setting priority for the flat camera renderable to 0 (render first?) and doesn't seem to work.

Any helpful insights would be great.

**Comment by romainguy** [comment]
You cannot rely on insertion order for the drawing order. You either need to use bounding boxes for the sorting to occur properly, or use priorities. In your case it would be better to draw the camera plane last (priority 7) so it's drawn depth-tested after all the other opaque objects have been renderer. This will be better for performance. Transparent objects will then be rendered on top of the camera. Things to check:

- Is your camera plane opaque or transparent? It should be opaque
- What is the Z value of your camera plane? It should be drawn at Z=1 in the `vertexDomain` called `device` 
- Make sure you set the priority properly (but since transparent objects were drawn behind the camera plane, it would indicate the issue is either the Z or the blending)

The artifact you see is because you are not drawing every pixel on screen when you remove the camera plane.

**Comment by MarkMurillo** [comment]
Thanks, I took your advice and set the `vertexDomain` to `device` and changed the Z value for the vertices to 1.0f which seems to work. J had to adjust the vertices since its now in normalized device coord space but it works with some minor artifacts:

As you can see in the video there seems to be some green blips that appear. Not sure what's going on [here](https://streamable.com/mw8cbx)...

I've set the priority for the camera plane to 7, but left the other renderables' priority to default (I guess it's 4, and also im not sure how to set the priority for assets loaded from gltf). Also, not sure if it's related but the plane renderables (grid) and some 2d quads for videos are all masked (with threshold 0.5) and not transparent. The reason for this is to enable r/g/b chromakeys.

**Comment by romainguy** [comment]
Masked objects won't be blended and will be treated as opaque objects so that should be fine. The default priority is indeed 4.

For the green issue, try to use a Z value slightly lower than 1 to see if it helps (0.99f for instance, it just need to be high enough to not intersect items in the scene).

Last but not least you could try to set the camera plane priority to 0 and to disable depth testing on its material. This is not as good for performance but it should always work (and you can disable depthWrite too).

**Comment by MarkMurillo** [comment]
I just want to write that the artifact wasn't actually fixed, but It was only showing for the model I was using. All other GLTF models had no artifacts. This was more evident when I tried to apply IBL, and it was not lighting the plane model I was using at all, but all other GLTF models were fine. Additionally, the plane model I was using was supposed to have an animation, but it failed to load the animation as well. I suspect it is an issue of exporting an originally USDZ to GLTF. Anyways, the disabling the ssao options had nothing to do with the artifacts (and was still showing it afterwards). Just thought I'd set the record straight
