### ISSUE TITLE
Support more than 4 blend shapes

### ISSUE THREAD

**Issue by wes-nz** [google/filament#4772]
### Feature Request
The ability to access the underlying cgltf data on Android.

I need to find a way around the 4 blend shapes limitation. Accessing the underlying cgltf data to update the vertex manually seems to be the most straight forward solution (`asset->getSourceAsset()` and potentially more?).

Related discussions about the state of blend shapes, [here](https://github.com/google/filament/issues/1487) and [here](https://github.com/google/filament/issues/3726) 

**Describe the solution you'd like**
- Ideally morph targets via data texture ([mentioned here](https://github.com/google/filament/issues/1487#issuecomment-533820189) - long-term solution)
or
- The ability the access the underlying cgltf data to update the vertex manually (short-term solution).
or
- Support more than 4 blend shapes out of the box via `RenderableManager::setMorphWeights()`

**Describe alternatives you've considered**
I tried converting the morphs to animations inside the GLTF file, however animations aren't blending making it an unviable solution.
[Discussion here](https://github.com/google/filament/discussions/4754)

**OS and backend**
Android.

Thanks.

**Comment by akbiggs** [comment]
ARKit is another example of a feature that currently supports 52 blend shapes for their face detection.  https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation

If we want to take that data and apply it to a GLTF mesh rendered using Filament, I think this limitation makes it difficult, but I might be misunderstanding.

**Comment by pixelflinger** [comment]
Do this this we would need:
- store the weights in their own UBOs. We could store eight fp16 weights per UBO "line". With 56 weights, that would give us a maximum of 146 sets of blend shapes (i.e. we could have 146 renderables, each with 56 different blend shapes). This would be a hard limit like we have for lights for instance.
- we'd store an index to the set of 56 weights and a count in the per-renderable UBO (instead of the 4 weights)
- we'd also need a buffer containing the vertex data, for this we'd use an SSBO (so it would work only on ES3.1+), this buffer would be provided by the user and would need to be formatted properly (in terms for data layout and format, e.g. vec4 positions, vec4 normals, interleaved). In the vertex shader we would do vertex pulling using `gl_VertexID`.

**Comment by will4621d** [comment]
@wes-nz @akbiggs Here's a solution I found may give some hint to you, https://blog.csdn.net/kaelsass/article/details/117363508, let me know if it helps.

**Comment by daemyung** [comment]
@wes-nz, @akbiggs Please try this patch(https://github.com/daemyung/filament/tree/morphing).

**Comment by wes-nz** [comment]
Thanks @daemyung for all your work 👍

**Comment by babefish2008** [comment]
> @wes-nz, @akbiggs Please try this patch: https://github.com/daemyung/filament/tree/morphing.

Thanks your great effort, I am wondering if the feature Morphing on GPU has been full completed or not? and will it be merged to  filament mater?

**Comment by daemyung** [comment]
@babefish2008 gltf_viewer is an example using this feature.
