### ISSUE TITLE
RenderableManager::setBlendOrderAt not work?

### ISSUE THREAD

**Issue by noseeevil** [google/filament#4877]
hello! 
RenderableManager::setBlendOrderAt - for primitives in the same model? or I can blend several models with it? 

I thought about second option, but its not work for me, or I made mistakes in my code

I have two models, this models are the same, but first model have position 0,0,-8, and second have position 0,0,-6, and second model drawing after first, but can I change it? and how? (I want drawing first model after second model)

I loaded both models and tried change this options
`RenderableManager& rm = engine->getRenderableManager();`

` auto renderableFirst = rm.getInstance(app.glbFirst->getRoot());`
` auto renderableSecond = rm.getInstance(app.glbSecond->getRoot());`

` rm.setBlendOrderAt(renderableFirst, 0, 5);`
` rm.setBlendOrderAt(renderableSecond, 0, 1);`

![Screen Shot 2021-11-19 at 14 08 51](https://user-images.githubusercontent.com/16321108/142615015-ff4a6d70-2b10-4a95-9daf-d6b3582aec10.png)

**Comment by romainguy** [comment]
`setBlendOrderAt` works but it only applies to materials that have blending enabled. Your example uses opaque materials, that's why it has no effect. If you want to change their rendering order, use the render priority instead (of course depth testing will then become an issue here, so you may want/need to turn that off).
