### ISSUE TITLE
utils::slog not threadsafe but used by multiple threads, wrong snprintf usage

### ISSUE THREAD

**Issue by RYDB3RG** [google/filament#4992]
Hi,

not sure if `matc`-only, but its using `slog` concurrently, leading to resize issues:
![image](https://user-images.githubusercontent.com/7002848/147218790-b330672e-8e96-4f96-9621-8980c0f658ba.png)

And isn't code like this an issue aswell:
https://github.com/google/filament/blob/b5c4b30ff6332193070a759b5c1c8ac6637ac80e/libs/utils/src/ostream.cpp#L128
because it tells `snprintf` that `buf.curr` has `buf.size` capacity, but isn't this is only true when `buf.curr` points to the begin of the buffer, which isn't always the case?

**Comment by bejado** [comment]
Regarding `snprintf`, `buf.size` stores the [remaining size](https://github.com/google/filament/blob/2f3aac29da7e833378d75dd89fadcfc4bcb11623/libs/utils/include/utils/ostream.h#L75) of the buffer, so I believe the implementation is correct.

At one point `utils::slog` was using thread-local storage, but looks like it was reverted here: https://github.com/google/filament/commit/ee7feff9cc7551f7dece2f58638a0b49e48c549c. @pixelflinger do you have any thoughts?

**Comment by pixelflinger** [comment]
A long time ago loggers were not thread-safe, then we made them thread-safe, but ran into an issue when several .so that each include `libutils.a` are used. In that case, one of the `slog` wasn't initialized at all, which caused crashes (e.g. when using filament.so and gltfio.so).

The real solution would be to deliver all our libraries as `.so`, or as `.a` and let the user create their own `.so`. We're doing this hybrid thing where we're distributing several `.so` that each contain `libutils.a` and that causes issues with `thread_local`.

I believe when we are not using `thread_local` what happens is that we end-up having two different `slog`, which is fine (in that case).
Unfortunately, the only sensible thing to do right now is to make `ostream` thread-safe, so at least it doesn't crash or corrupt memory -- but the output will be garbled.
