### ISSUE TITLE
ubershaderLoader.destroy() crashes when called after assetLoader.destroy()

### ISSUE THREAD

**Issue by stevexbritton** [google/filament#5132]
Hi,

Android Filament 1.12.8

I create an AssetLoader with an UbershaderLoader (previously, Filament 1.10.6, I used a MaterialProvider instance).
  val materialProvider = UbershaderLoader(engine) // Pre Filament 1.10.7 MaterialProvider(engine)
  val assetLoader = AssetLoader(engine, materialProvider, EntityManager.get())

Filament now crashes when I destroy the UbershaderLoader (did not happen with the old MaterialProvider)
  assetLoader.destroy()
  materialProvider.destroy()
    --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6f635f61766152 in tid 24346 (filamenttracker), pid 24346 (filamenttracker)

Is this a bug or do I not need to call the UbershaderLoader's destroy method if I have destroyed the AssetLoader?

Thanks in advance,
Steve

**Comment by prideout** [comment]
The JNI implementation for `assetLoader.destroy()` auto-destroys the native material provider (see `nDestroyAssetLoader`).

I feel that users may wish to preserve the material cache from one run to another, and that it would be good to decouple its lifetime from AssetLoader.

So, IMO this is a real bug and the fix is:

1) Remove `delete loader->getMaterialProvider();` from nDestroyAssetLoader, and
2) Add a `destroy()` method to the `MaterialProvider` Java interface, and
3) Update all documentation (e.g. the javadoc for the AssetLoader class) and examples by adding an explicit destroy() call.

@stevexbritton In the mean time you can simply omit your call to `ubershaderLoader.destroy()`.  There should be no memory leak.
