### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by amerkoleci** [google/filament#516]
**Is your feature request related to a problem? Please describe.**
There are no related problems

**Describe the solution you'd like**
Update from VS2015 to VS2017

**Describe alternatives you've considered**
Understand if VS2017 clang works well or better use MSVC toolkit

**OS and backend**
This is related to windows OS.

**Comment by shartte** [comment]
I have been using VS2017 with Filament without much issues so far, what in particular is this issue about?
Is it about the pre-built packages?

**Comment by amerkoleci** [comment]
I mean compile filament using clang vs2017 not about usage

**Comment by shartte** [comment]
Yes, but that is already working... I am compiling filament using clang-cl and VS2017, using the instructions found on the main page.

**Comment by romainguy** [comment]
Our instructions use Visual Studio 2015 because that's what our CI environment offers. According to @shartte it works in Visual Studio 2017 as well (which makes sense, we don't use anything VS specific I believe). Please open a new bug with more specific information if it doesn't work in VS 2017. Thanks!

**Comment by amerkoleci** [comment]
Okay, thank you!
