### ISSUE TITLE
Adding a material library with common materials

### ISSUE THREAD

**Issue by Orctonk** [google/filament#5177]
**Is your feature request related to a problem? Please describe.**
I would like a collection of some materials to quickly assign common materials to renderables. Sort of like the materials showcased in the README
![Material showcase](https://github.com/google/filament/blob/main/docs/images/samples/example_materials2.jpg)

**Describe the solution you'd like**
One idea might be to add an optional library with material definitions which could be accessed similarly to how the material registry is used in the filamesh library

**Describe alternatives you've considered**
One alternative could be to look at reference values for other renderers as well as the ones provided for filament and manually create each material when needed, however this approach is harder to maintain and does not help anyone else that might need a similar solution.

**OS and backend**
This feature would not be platform specific

**Comment by romainguy** [comment]
Thanks for your suggestion but this is beyond the scope of this project. Since Filament supports a common PBR model, you can easily import texture sets from Substance Share/Source, [Polyhaven](https://polyhaven.com/textures), etc. You only need one material for them that assigns baseColor, metallic, etc. You can also just use the glTF format via our gltfio library.
