### ISSUE TITLE
How to remove Shadow casted by HDR image.

### ISSUE THREAD

**Issue by chirag-qs** [google/filament#5196]
**Current behavior**
Currently I am using ModelViewer class to load my gltf Model and IBL for lighting, and for that I am using HDR images. but current IBL images show shadow of the HDR images on my model and that looks little weird. I have attached video below.

https://user-images.githubusercontent.com/86815724/153827864-07792959-5519-472b-85c0-36ddd752e3ee.mp4

**Expected behavior**
But actually I wants to apply lighting without having shadow on the mode. Similar to below video.

https://user-images.githubusercontent.com/86815724/153828060-31e20666-1d5c-45e8-89d3-ec246c46f71b.mp4

I have tried some HDR images but shadow/reflection is always there. so is there are other way to remove shadow/reflection and apply lighting only ?  

Also if you can suggest any HDR image with minimal shadow shadow/reflection, it will be really helpful.

Thanks in Advance.

**Comment by romainguy** [comment]
There are no "shadows", what you are seeing is the result of lighting being applied. If the lighting you are getting is not to your liking, you should use a different IBL. The second video you are showing still shows reflections, it just happens to not have darker areas because the IBL doesn't have them.
