### ISSUE TITLE
Shadowmap has usage=COLOR_ATTACHMENT and format=DEPTH16

### ISSUE THREAD

**Issue by prideout** [google/filament#5287]
This can be reproduced on Android by running `sample-gltf-viewer` with the default model and OpenGL and hacking `FrameGraphTexture::create` by adding:

```
    if (descriptor.format == backend::TextureFormat::DEPTH16 && !(usage & backend::TextureUsage::DEPTH_ATTACHMENT)) {
        utils::slog.e << "strangeness seen with " << name << utils::io::endl;
    }
```

**Comment by pixelflinger** [comment]
after investigation this is a normal condition. In fac the usage is not "COLOR", it's SAMPLEABLE. This happens because there are no objects in the scene so the shadowpass is canceled, in turn the DEPTH_ATTACHMENT usage is not set. But the texture is SAMPLEABLE because it used in the colorpass technically, even if not actually sampled.
