### ISSUE TITLE
Why filament choose to build HUGE STATIC libs, rather than SMALLER SHARED libs?

### ISSUE THREAD

**Issue by jiapei100** [google/filament#5807]
Given an example: [utils CMakeLists.txt](https://github.com/google/filament/blob/main/libs/camutils/CMakeLists.txt)

What is the particular reason to do 

```CMake
add_library(${TARGET} STATIC ${PUBLIC_HDRS} ${SRCS})

target_link_libraries(${TARGET} PUBLIC math)
```

?? Intentionally to make **camutils** a little **bigger**, with **math** lib included??? 

And, a bunch of STATIC libs **ALL** grow  bigger??

**Comment by romainguy** [comment]
In this particular case it doesn't matter since libmath is a header only library. We use static libs to *reduce* overall size when the final executables are assembled as a lot of code can be removed by the linker then. Keeping size small on Android is one of our primary concerns. We regularly talk about providing shared libraries as well but there's no firm plan at the moment.
