### ISSUE TITLE
Meshes with multiple texture maps fail to load properly w/ WebGL backend

### ISSUE THREAD

**Issue by cpheinrich** [google/filament#6077]
**Describe the bug**

Meshes that have multiple texture maps do not load correctly with WebGL backend. It appears that only one of the texture files is loaded, and the other ones are discarded. This manifests as having many triangles appear black:
![Screen Shot 2022-09-15 at 1 44 29 PM](https://user-images.githubusercontent.com/12475454/190505184-f8fd425d-5e49-46c2-864e-6fa9f5082240.png)

The issue only appears to affect WebGL as the OpenGL android backend is fine. We have not tested Metal backend for this issue.

**To Reproduce**

Load a mesh with multiple texture files into a filament web viewer and observer. Here is an example 

[rv.glb.zip](https://github.com/google/filament/files/9578911/rv.glb.zip)

**Expected behavior**

Expected all texture maps to be properly loaded

**Screenshots**
You can test out the problem live here. Here is the mesh loaded with ThreeJS

https://poly.cam/capture/FF23A840-11F2-4768-8EDF-C103A301DBC9

And here it is loaded with filament:

https://poly.cam/polykit/FF23A840-11F2-4768-8EDF-C103A301DBC9

This mesh's texture is split up into 2 texture maps:
<img width="375" alt="Screen Shot 2022-09-15 at 1 46 10 PM" src="https://user-images.githubusercontent.com/12475454/190505535-4781e978-50ba-4fa5-a3f4-59ac3c3b8f0d.png">
df0e-ef47-494b-a6ec-8e4b3c146524.png">

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: All tested
 - GPU: All tested
 - Backend: WebGL

**Additional context**

**Comment by romainguy** [comment]
It works fine in our instance of the viewer at google.github.io/filament:

<img width="784" alt="Screen Shot 2022-09-15 at 2 03 16 PM" src="https://user-images.githubusercontent.com/869684/190508288-cf66b97d-01cf-4fd1-a4fb-3fbb7c7d3b85.png">

Maybe there's something different about how you setup the viewer?

@prideout Any idea? Hard to debug since it's fine on our end.

**Comment by cpheinrich** [comment]
> It works fine in our instance of the viewer at google.github.io/filament:
> 
> <img alt="Screen Shot 2022-09-15 at 2 03 16 PM" width="784" src="https://user-images.githubusercontent.com/869684/190508288-cf66b97d-01cf-4fd1-a4fb-3fbb7c7d3b85.png">
> 
> Maybe there's something different about how you setup the viewer?
> 
> @prideout Any idea? Hard to debug since it's fine on our end.

Thanks for checking this out and clarifying @romainguy , that narrows things down for us quite a bit! @prideout if you do have any suggestions for where we should look on our end please let us know! We'll try to track down the issue on our side and will update the ticket. 

Unrelated to this issue, I'd like to an offer a suggestion to make the default color grading linear. We were struggling to identify why the render quality of our meshes always looked worse in filament than in threejs but it turns out that making this small change improved rendering quality of meshes substantially. Maybe you are already aware, just fyi. 

![Screen Shot 2022-09-15 at 2 12 00 PM](https://user-images.githubusercontent.com/12475454/190509599-4398f56c-b913-420c-8d64-f835b3864b82.png)


Thanks again for the ongoing development work!!

**Comment by romainguy** [comment]
I strongly disagree with making linear the default tone mapping and I would argue against using the term "rendering quality" here. The problem is whether the meshes have been authored for linear presentation, whether the used already tone mapped textures, etc. Linear is strictly "worse" for the common use case of Filament (PBR rendering using dynamic lights). Linear only makes sense for unlit subjects and/or photogrammetry.

**Comment by romainguy** [comment]
BTW I would also recommend you don't use `ULTRA` quality for your use case, especially for linear rendering. `ULTRA` is only useful if you use non-linear tone mapping and/or color grading features (curves, etc.). You'll save quite a bit of memory and performance sticking with the default setting.

**Comment by cpheinrich** [comment]
> BTW I would also recommend you don't use `ULTRA` quality for your use case, especially for linear rendering. `ULTRA` is only useful if you use non-linear tone mapping and/or color grading features (curves, etc.). You'll save quite a bit of memory and performance sticking with the default setting.

Awesome, thanks for the tip!

**Comment by cpheinrich** [comment]
> I strongly disagree with making linear the default tone mapping and I would argue against using the term "rendering quality" here. The problem is whether the meshes have been authored for linear presentation, whether the used already tone mapped textures, etc. Linear is strictly "worse" for the common use case of Filament (PBR rendering using dynamic lights). Linear only makes sense for unlit subjects and/or photogrammetry.

Thanks for clarifying. This was not on our radar because all of our meshes are photogrammetry and/or unlit. Could be a useful suggestion to add to the docs though that linear mapping will work best for photogrammetry scans given that photogrammetry is an increasingly common way of authoring 3D content (will probably be the most common form soon) and it's not-obvious given that other renderers like ThreeJS and SceneKit seem to default to linear

**Comment by romainguy** [comment]
For reference, here's a PBR scene in linear:
<img width="1834" alt="Screen Shot 2022-09-15 at 2 37 44 PM" src="https://user-images.githubusercontent.com/869684/190513452-20b4ffea-2621-4e9b-b58d-65b4e9651207.png">

And the same scene with a non-linear tone mapper:
<img width="1834" alt="Screen Shot 2022-09-15 at 2 38 07 PM" src="https://user-images.githubusercontent.com/869684/190513489-22f731ef-023f-4db6-bd8b-8a135edf0559.png">

Note how the sun is clipped in the first image, and how blue hues in the sky are completely distorted. You also get a "washed out" appearance on the rest of the image.

**Comment by omri-polycam** [comment]
Greetings @romainguy, I am the Polycam engineer in charge of fixing this issue and work with @cpheinrich. So after a bit of digging and debugging I found out the root of the problem is that we aren't calling `filament::gltfio::StbProvider::updateQueue()`. This is leading to `decodeSingleTexture()` only being called once and thus only 1 of the multiple textures is loaded. That also explains why we are only seeing this problem on web as the other platforms do support multithreading and go through different code paths inside filament and use the job system for texture decoding. Below is the revised code for our mesh loading that fixes the problem:

```
  asset_ = asset_loader_->createAsset(bytes, size);
  auto resource_loader = gltfio::ResourceLoader({.engine = engine_, .normalizeSkinningWeights = true});
  resource_loader.addTextureProvider("image/jpeg", texture_provider_);
  scene_->addEntities(asset_->getEntities(), asset_->getEntityCount());
  while(texture_provider_->getDecodedCount() < texture_provider_->getPushedCount()) {
    texture_provider_->updateQueue();
  }
  asset_->releaseSourceData();

```

The `while` loop is new and fixes the problem. Before I commit this code, I'd just like to verify that I am using `updateQueue()` correctly and my logic is sound. Thanks again for your help!

**Comment by prideout** [comment]
Hi @omri-polycam Normally I'd expect to see a `resourceLoader.asyncBeginLoad()` after the resource loader is constructed.  Then, you'd call `resourceLoader.asyncUpdateLoad()` in loop (or in a timer, if you want to yield to the UI).  By calling `updateQueue()` on the texture plugin directly, you're bypassing the resource loader layer.

Sounds like you're using emscripten, since you're not using our JavaScript bindings or our Web Component.  That's fine, but they do simplify some of this stuff so you can look at their implementation for inspiration.  For example, here's how our JavaScript bindings do this (you can mentally translate the JS to C++)

https://github.com/google/filament/blob/main/web/filament-js/extensions.js#L554

**Comment by omri-polycam** [comment]
HI @prideout ! Thanks for the advice. I'll add the initial `asyncBeginLoad()` and modify the loop to call `asyncUpdateLoad()` until `asyncGetLoadProgress() >= 1.0f`.

**Comment by cpheinrich** [comment]
Thanks a lot for your help @romainguy and @prideout!  Calling out that this was indeed an issue in our implementation of the filament web viewer and not an issue in the filament library. We've got it fixed on end now per the comments above.

**Comment by romainguy** [comment]
Glad you were able to fix it! Don't hesitate if you run into more issues and/or if you have questions.
