### ISSUE TITLE
Add Vsync callback API to Filament

### ISSUE THREAD

**Issue by romainguy** [google/filament#636]
We currently rely on the app somehow syncing rendering to vsync. We should have a Filament API to handle this cross platform. One reason why it matters that we do it ourselves is that some platforms may need to the GL context, for instance macOS: https://developer.apple.com/library/archive/qa/qa1385/_index.html

**Comment by prideout** [comment]
In addition to a callback, maybe we should proffer an easy-to-use API that would simply be a SwapChain flag. This flag would mean: "please wait for vsync when ending a frame".  This would cover a lot of common use cases and would reduce the amount of boilerplate that applications need to write.

Note that, starting with Mojave, we _must_ use `CVDisplayLink` to implement this instead of `NSOpenGLContextParameterSwapInterval`. To implement my flag idea, we would signal a condition variable in our display link callback.

Side note: we added a presentation callback API to `Renderer` in #1760, but I think this was fulfilling a different need that is unrelated to vsync.
