### ISSUE TITLE
Applying rotation to projection matrix changes spotlight

### ISSUE THREAD

**Issue by kpeeters** [google/filament#6390]
I am trying to rotate the final rendered image by pi/2 or -pi/2 by adjusting the projection matrix. That works fine, except that light produced by spotlights changes. This is what I do:

    math::mat4 rot;
    double angle = 3.1415/2;
    rot[0][0]= std::cos(angle);
    rot[0][1]=-std::sin(angle);
    rot[1][0]= std::sin(angle);
    rot[1][1]= std::cos(angle);
    rot[2][2]=1;
    rot[3][3]=1;

    auto projmat = camera->getProjectionMatrix();
    camera->setCustomProjection(rot * projmat, camera_near, camera_far);

Directional lights behave fine (i.e. their effect looks the same with or without the rotation), it's just the spots that change.

Am I doing this wrong?

**Comment by romainguy** [comment]
Doing this probably impacts the froxels and how we find what part of the image are lit by each spotlight. @pixelflinger

**Comment by kpeeters** [comment]
@romainguy Yes, it sounds it's something like that. In any case, I was expecting this kind of post-transformation to not influence anything in the final image, except a 90 degree rotation.

**Comment by pixelflinger** [comment]
I'm not sure if this will affect your problem with the spotlights, but it's not correct to set a custom projection this way.

This is because you're setting the same projection for viewing and culling and that projection has an infinite fare (because you got it from `getProjectionMatrix()`. Instead, you should use the overload of `setCustomProjection` that takes two matrices and get them from `getProjectionMatrix()` and `getCullingProjectionMatrix()` and rotate those.

Try that and let us know if that changes anything  (probably not, I'm guessing).

I think we do have assumptions in a few places about the shape of the projection matrix, I would have to look into this in more details.

**Comment by kpeeters** [comment]
Using the `setCustomProjection` that accepts two matrices does unfortunately not resolve the issue.

**Comment by kpeeters** [comment]
If there is a better way to rotate the image by multiples of pi/2 then that would work too (in other words, a cleaner way to apply a 2d transformation to the final render). The problem I am trying to solve is to adjust for a rotated view on a mobile device. I have a view which has a fixed orientation (I want to keep it that way to avoid re-creating the swapchain on every orientation change) and thus need to rotate filament's output to keep it so that the top of the view points in the physical upwards direction. More in https://github.com/google/filament/discussions/6348.

**Comment by pixelflinger** [comment]
Can you send a few screenshots of the working and not working case with spotlights?

**Comment by pixelflinger** [comment]
Looking at the Froxelization code, I'm pretty sure  it won't work if any transform is applied to the projection and I think that's already a bug with `Camera::setScaling` and `Camera::setShift`, except it'll be less jarring I think.
It won't be a trivial fix, so it'll take a few weeks maybe more.

I believe the issue is that we express the froxel planes in clip-space transformed to camera space and we make assumptions on their equation. We probably need to start from camera space directly. 

In any case I'm still interested in screenshots showing the problem.

**Comment by kpeeters** [comment]
Sorry for the wait. Attached is a clip that starts off with the device in landscape, with an unrotated projection matrix. The device is then rotated to portrait, keeping the rotation of the view fixed by applying a transform to the view that counteracts the device rotation (this step is irrelevant for the bug; the rendering issue appears with or without this). A rotation is applied to the projection matrix to keep the scene top at the top of the device, and this causes the scene to darken because the spotlight is no longer handled correctly, except for a little square in the middle. That square jumps around a bit when updates are made to the scene.

https://user-images.githubusercontent.com/5918606/211513220-5835abe4-ed7f-4e61-a0fd-e04785d93be6.mp4
