### ISSUE TITLE
Android: ktx1reader and ktx2reader classes not included in Android release libraries

### ISSUE THREAD

**Issue by BStringhamVRSK** [google/filament#6565]
We are using the Android NDK to link our C++ code to the Filament libraries.  We extract the `libfilament-jni.so` library from the release AAR files and link against that in our project.
If we exclude portions of our code that reference `ktx1reader` and `ktx2reader`, then the rest of the filament libraries link in just fine.  But, if we try to use our ktx code, it just crashes.

As a test, we created a small JAVA app that loads our C++ wrapper library (which references Filament ktx code).  In that test app, we get this error message:

`E/AndroidRuntime: FATAL EXCEPTION: main    Process: com.example.javanativelibraryapplication, PID: 11512    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN9ktxreader10Ktx2ReaderC1ERN8filament6EngineEb" referenced by "/data/app/~~li56r5XIViSFSHLcr5od5g==/com.example.javanativelibraryapplication-3OVmM2KOHs-GGwoB7PRWFw==/base.apk!/lib/x86/libFilamentAPI.so"`

We believe this is caused by not having `ktx1reader` and `ktx2reader` publicly accessible in the libraries.

Would it be possible to expose those classes in the Android release libraries?

 - OS: Android
 - Backend: OpenGL

**Comment by romainguy** [comment]
`libfilament-jni` isn't designed to preserver the symbols so that C++ code could link against it, I'm actually surprised you got it to work. Anyway, `ktx1reader` and `ktx2reader` are part of `filament-utils` and are therefore in `libfilament-utils-jni.so`.

Even if this doesn't work, our goal is NOT to expose C++ symbols via our JNI libraries. We only want to expose the symboles required for JNI to work.
