### ISSUE TITLE
【OPENGL】culling not work when running gltf_viewer on PC

### ISSUE THREAD

**Issue by dandingol03** [google/filament#6641]
**Describe the bug**
I set the `culling` to _front_ in lit_opaque.mat, but the front mesh of model is not culled. I found the reason why the culling mode is invalid. After the `UbershaderLoader` initial material, it will override the origin material's culling mode. I can't understand the reason why `UbershaderLoader` override the culling in my mat file to `back` or `none`
**To Reproduce**
1. just set the `culling` to false in mat file

**Expected behavior**
the font mesh of model is culled 

use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: [MAC M1]
 - Backend: [OpenGL]

**Additional context**
- _filament version_: 1.12.5
- link of model : [tixue](https://drive.google.com/file/d/1lRqTk71s9QMPPySj41os1sf1m4dRse6l/view?usp=share_link)

**Comment by bejado** [comment]
Is this what you're referring to? This is by design.
https://github.com/google/filament/blob/0759797e618afa040b1f7937e438ed2a8bf62052/libs/gltfio/src/UbershaderProvider.cpp#L208-L210

See the glTF specification on [double-sided](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#double-sided). You may need to implement your own subclass of `MaterialProvider` to prevent this.
