### ISSUE TITLE
memory increase continuously

### ISSUE THREAD

**Issue by August1996** [google/filament#7318]
<img width="949" alt="image" src="https://github.com/google/filament/assets/15972489/d9a59e90-2f71-4cac-a5fe-b44fb600cc74">

I render a very simple box model in `sample-gltf-viewer` with version 1.45.0, the memory will increase continuously until achieve high level. 

[box model](https://github.com/google/filament/files/13214200/scene.glb.zip)

@pixelflinger @bejado

**Comment by August1996** [comment]
@pixelflinger @bejado 
The issus was introduce by this commit. [Implement preliminary support for instanced stere](https://github.com/google/filament/pull/6967/files)

**Comment by pixelflinger** [comment]
The description says the memory "increases continuously" but according to your graph, it doesn't. At around 15 seconds is stops increasing. So it doesn't look like a leak.
I think what's happening is just that there are more shader variants being loaded, due to the STE variant.
More memory is used by the shaders, but there is no leak.

**Comment by August1996** [comment]
> box model

Yes, the memory does not keep increasing, but when I see the model rendering, the memory keeps increasing. As shown in the picture, it has grown from  92.7 MB to more than 200 MB. 

And, this is just rendering a very simple model, only 12 triangles, no complex materials
