### ISSUE TITLE
Spherical Harmonics incorrect for some environment maps?

### ISSUE THREAD

**Issue by MiiBond** [google/filament#744]
**Describe the bug**
The spherical harmonics coefficients produced by cmgen usually appear correctly when rendered in Babylon.js or other engines. However, the `ennis.exr` (http://gl.ict.usc.edu/data/highresprobes/) environment map produces SH coeffs that result in very dark lighting on the positive Z axis (perhaps even negative lighting). This occurs in both Babylon.js as well as this online SH visualizer:
[SH visualization of ennis.exr](http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization?sh=1.287898417917449,1.224812344906915,1.284373356239353,0.346492805809427,0.437322665316237,0.596579229692604,2.031314720116359,2.035335963181135,2.19559945524799,-0.134856038723891,-0.133884756744807,-0.137855965720924,-0.04962776332485,-0.04995879165701,-0.05888679768646,0.729462362127353,0.816352125430164,1.049210072745487,0.560397563988677,0.551110511600047,0.578835392533332,-0.22058370118399,-0.199970232296532,-0.199938849886581,0.010848602074688,-0.013719170403842,-0.052358504871756,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0&exposure=5.256126508597484&quaternion=-0.11284500881172371,0.8326029362432015,-0.05837982339342862,0.5391012606299657,3.7870083412149294)
I'm wondering if this is somehow related to there being such a large range in values in this particular image.

**To Reproduce**
1. Generate the SH coeffs for ennis.exr using the cmgen command line tool.
2. Enter them on the http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization to visualize the results.

**Expected behavior**
The dark side of the sphere should at least have some lighting, especially with high exposure but it always appears black. Perhaps I have a fundamental misunderstanding of SH's that's affecting my expectations.

**Screenshots**
<img width="388" alt="default exposure" src="https://user-images.githubusercontent.com/1069125/51766832-68f86700-2090-11e9-84f5-daad8f50f3f0.png">
<img width="393" alt="high exposure" src="https://user-images.githubusercontent.com/1069125/51766833-6990fd80-2090-11e9-854d-36f807bacdd9.png">

**Comment by romainguy** [comment]
@pixelflinger is our SH specialist.

A couple of things to note:
- We pre-divide the SH by π so we don't have to do it in the shaders. I don't know if those other engines do this or re-divide by π at runtime (which wouldn't help with the darkening you're seeing for ennis.exr)
- Our SH reconstruction in the shaders guards against negative lighting by doing a `max(…, 0.0)`

**Comment by romainguy** [comment]
We also premultiply the SH by the basis (we basically output colors), not sure what Babylon, etc. expect.

**Comment by MiiBond** [comment]
I actually multiply by π when exporting from Dimension to get things to look correct in Babylon but I wouldn't expect any colours near (and definitely not below) zero for this image so it seems like more than just a scale factor issue, no?

**Comment by MiiBond** [comment]
Okay, so using `./cmgen -f .hdr -i --sh-output=ennisIr.hdr ennis.exr` to reconstruct the irradiance from the SH coeffs, I get a reasonable result.
<img width="400" alt="screen shot 2019-01-25 at 12 33 23 pm" src="https://user-images.githubusercontent.com/1069125/51771396-b7f8c900-209d-11e9-825e-bf1b2b90d8ac.png">

So, this issue is due to my lack of understanding in how these SH coeffs should be translated for use by Babylon or that online visualizer.

**Comment by MiiBond** [comment]
Using the output of this call as .txt as @romainguy suggested to me, gives SH coeffs that work beautifully in Babylon. So, problem solved!
Thanks, @romainguy !

**Comment by MiiBond** [comment]
I've changed my code from `computeIrradianceSH3Bands` to `computeSH` to get the correct SH coefficients for use in Babylon.js (and indeed, the colour values look much better). However, now the irradiance lighting looks flipped. I had expected the orientation to not change...
I can get a matching orientation if I change `computeSH` to negate the x and y coords of the direction vector. Obviously, this doesn't seem like a correct solution. Any ideas what might cause this, @pixelflinger?

**Comment by romainguy** [comment]
Looking at the code of the two methods it seems to be doing exactly the same thing. The difference could be in `computeShBasis()` invoked by `computeSH()`.

**Comment by romainguy** [comment]
Interestingly, when I render the SH using cmgen and the two techniques, I get the same result both times:

`./cmgen --sh-shader --sh-output=test1.png Runyon.exr`

![test1](https://user-images.githubusercontent.com/869684/51781050-daeca280-20c8-11e9-84b4-f5862afb4bda.png)

`./cmgen --sh-irradiance --sh-output=test2.png Runyon.exr`

![test2](https://user-images.githubusercontent.com/869684/51781055-e213b080-20c8-11e9-9e6f-fe752c04cf7a.png)

**Comment by MiiBond** [comment]
Hmmm, I must be doing something wrong. I'll take another look tomorrow.
Thanks for checking.

**Comment by romainguy** [comment]
Could still be on our side if we mirror twice.

**Comment by TimvanScherpenzeel** [comment]
Perhaps I'm missing something very basic but when using the [SH visualizer the Y-axis appears to be flipped (with and without `--no-mirror`)](http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization?sh=0.713998716281181,0.74925760171112,0.754251028455051,-0.321871438298009,-0.330726032943991,-0.421331030719026,0.265904137307755,0.252324096046643,0.204189459655912,0.171010382451126,0.161721505781993,0.135598157767314,-0.069494804432808,-0.066861911824577,-0.058643685785537,-0.113266820775476,-0.10704625297995,-0.09171473283682,0.038271258414459,0.037150768223298,0.027120352660517,0.075390382015998,0.071774142223014,0.060056170163255,-0.001016623993141,-0.000067339756464,-0.004659992841745,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0&exposure=1&quaternion=0,0,0,1,3). The blue and white is the sky, the floor should be green. It has been generated from https://hdrihaven.com/hdri/?c=outdoor&h=green_point_park. Does this also have to do with the difference in reconstruction in Filament compared to this SH visualizer?

**Comment by romainguy** [comment]
The mirroring option is only horizontal. I don't know how that visualizer works. Is lighting flipped in other engines too? What's the coordinates system of that visualizer? Filament uses right handed, Y up.

**Comment by TimvanScherpenzeel** [comment]
Got it, the visualizer appears to use Three.js so it's right handed, Y-up.
I just [tested it on Cesium.js](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=pVhtc9u4Ef4rqL9I6sgUAIIgmdiZXpzkLm3SeGLnpr3zjQNJkMSaJDgk5Jd2/N/7AKREyXacu9bjkcjlvjz77C4I6FrV5DrTN7omx6TUN+REN9m6CH72suFg5m9PTGlVVup6MHp5UV6U17DS5XVWm7LQpf2oqi+fP8DBIAgm2/8fqqqZnKmiyvUbZdXk7Z7B5CpTtbqUl2phdV0aU17yq8tsmgdX9nbwso1RmLnOf4drr9dMTtVN2X0Gy3w68FgnE3K+yppdvKRQFblRDalqgwQbPSfrJiuX5EdjlrkeNORdliuvCY1/6ZkNyLnZaJM7s66JuSlfeOeMHJI3uMuNmhO70r1trXOtGk2GK2ur5sVksszsaj0NZqaYLH2kyaLTnXS6zSjwTjmcfl6X5OusWOqSHB7au0ofgxlcznWVm7vjSaXsamLNxKxttbZke58VaqmD1bz+GpBPAFSThakLZRuiak1U3hjSrKvK1FbPg/0oK51XX5061HJiKpsZUOkRhUB0rq60TxHaulawJzOjF4tsliEH+C9bBv52/g+CzLQXbHgpSFZ23fXXMwLymxVYI1Odm5ugLZQr+QdKyX4rniggbTJVhkNCAxZTEUUsoknIBOdj4mQyZBFzkpRylrayVKZSxpLyJI1l6Pq2C8Au2TcDHNKAShlFlMM0ScMkHBMn45wmCY2iWEgqEh+AxkkSRpSmXEjG490Az2dA4VUKmsYiTqKUtc5EFDMRUrhL4ihsZTIUaZJShJScRbsBGHk2A3iSUSjDkPGE0S4DKVIqWRiDqYi1soiyJBVUIGXK6U4AfsmfDQAXIY8TmbIYADfOYvylUczTNJGdTApEFUJEIQ35XgD2LEUiFJGIUuBFIqKjCOXkUUoZFSyKW1kEsiCIJR6yvQzo8xRRhhLAiMeCOYqIl/FEyjDhIWOR7GQxRwPRBIWQTO4G+E4N0JuSJugYSqXo+BYyTEWIpklFTOOOojiSPEWx0HXJbpE5/04GIgU14J+hl7oAEMapTJiUIok3GSSYFcwLozLlSb9+u0H7ln8axCxEGWMm0UEsaZs0FimPMFEsZozxlrQ4EhyjxxMMJdpi1C3c3xuykLPENXzC0wQ979GHIciW6BNwlHYZCc7QxRRP3GjL3v1z2LlElwi0OsziKPI4ecRDDqKkK7poB4xDCf2PNoswh7x3/ix0ZA8ugVxEYKFtdCZZjBFFMROWpu2awUJ4BfFxLGMsVVvvz82WG/pUpCLBzIQ8od1KI2UiWYo6IGa86fwEacgEEaMojHe8Pw+ehRzeuCNGxB14iiVVgqA0TtOom2ZMNhMxMIROu3f/HO+OlJjxKBEME98uw9QtOJjPhIP/tMvHadEwAhK0zA7259dljHrqQlAWpc6Tl7EYA4xZ41gGRCuTFOsOXhN4K/Ao6r3z7ywIMJAcnYdibceJonZhihEVsvMOqhAekyRYLKJ+nPZehMfkV4zX2I+B+/SX7grF95/+2km5v+K/bf2sdLZcWXhArA76qnqwOftJqzm2K6eZna0+mzx33I/J5mOTsamzJV65x48TDha1Kd7oZa11MzxkPASRAm8xlEwIt5KHMUVvtFBGu3uxj8rW2W3v87xWZeO2F02wegDq3LzLbvX8XY0NzrDFMnap9JR5j/DV7j+DZoZdRVDVWZHZ7Fo3gZrPh12cj07Vw/4xt4vhfy5Kgr91nZMX203iuBXu4nyxe7d5npVZsS5OAS4/y/6toYR1/6K8H7XIvEVQI5u7U8TLGh1g91IOF+ty5vZDQ68wIh0GX3ukWKs+k/bee3Mq2D39YkxBrGnh7BhiX12DK7/73qOhmaE45VmlZvrEezvZqr7s7Z0ZDyj5M0GKq6BQty26YGrWpavGWYX9nw5qlGbdjDug4HHdWLBaauXL4dz1UIKOIYf5TdZYVc404tSIQoNom5XHj2732Ddl8kSLoFjnNqvyu9d3pyYrbQdqtxbkSZytv/E3xnQ02km9a7e92KvAms8QoyeHWBDaUdgYVK4xv6l+yHfUO5pyY65+sMMnQO0NoCqXetjBGbdhxp4tVGb0pMvt1Awf8Pb+zdu/n78//+doy3JLU+PoyWYq/0nVhSmz2cn+arO7+LzcNt3GVs/Wuar3j1/O6tEJbrdjz7GPdx3pJ4/YWs2uGr+5R0NYTcyCuFOQaxWiqioHODccQc93b3y8mRX3l69h41rqB/uLLnEg2gxp8OhJa3TfJ4QZuNa19TB694UuprpucLzAgF2VZnaFExEx00bX12qa66YD1XG90Qh8TsOtn9Fu9q+z7iizQ4HxgjefPhKc1QrPPFhwsi/v8aUsioxTkzs9ZXaHCGtMPlVuSuZmtnaGwVLbt62P13fv58NBpzLYdMtDqI7hO4cJLdb0kMcb3z32zSqFI94Ua0g21afKrcDo4GGJ79FuLR6GAaxPW9p2w3jLYOty2LvYjTnEhPys8vV+kM2fL/KvztNv7dvMq77cV7zvbzdc3G9SeyKjwaOeGfRUnOH0OVONzbV7k5ybJQ7cr9fWAujgC47l/jg/X9cqJ/7IPBiTBU7HetwnNFvp2ZWe7+WTLcjwT089+L/G9aGDPzKzW/LQmMjrf4KEZVgvslLP/yCep+y6It67UtyPAuN+g7jBe7R/heq6NvWoA3qDvjY3gcKrx3ZPvCE+DsYHR429y/WrVvUvWeF+t3Av/mEQTKwuqhyrUTOZrlEOG8yaxpkdTTZGR/PsmmTz44uDBz9kXRyQWa6aBk8W69xvBC4OXh1NoL9n5n69wNB9wrqTqzunsmKvPrTCIAiOJrh9bNWNJdQhtW6aXh3ZqZnf+fu6y+bIzl992DQwwfrRtvDRBPJeo+f1KCvdDz3+p6CLg9q9d5AG7HGHt5e7Vre45v66sbpqHzDczZVVh1MwDdG1G7wXj1fiMfFPvlRQxvOBDzfwSTwNwepb6yKBPNyJ3xlm67BLFF91++UZwrcnzElaXv8L) and it appears to be flipped there as well (see the white chess piece).

<img width="600" alt="screen shot 2019-01-29 at 19 01 30" src="https://user-images.githubusercontent.com/11870513/51929582-dc83d680-23f8-11e9-867d-21fed3b2f628.png">

This is the case for me on the nightly build as well as the latest pre-release and stable release. I am using the 4K .hdr version as input.

**Comment by romainguy** [comment]
Our SH reconstruction is pretty simple:

```
vec3 Irradiance_SphericalHarmonics(const vec3 n) {
    return max(
          frameUniforms.iblSH[0]
#if SPHERICAL_HARMONICS_BANDS >= 2
        + frameUniforms.iblSH[1] * (n.y)
        + frameUniforms.iblSH[2] * (n.z)
        + frameUniforms.iblSH[3] * (n.x)
#endif
#if SPHERICAL_HARMONICS_BANDS >= 3
        + frameUniforms.iblSH[4] * (n.y * n.x)
        + frameUniforms.iblSH[5] * (n.y * n.z)
        + frameUniforms.iblSH[6] * (3.0 * n.z * n.z - 1.0)
        + frameUniforms.iblSH[7] * (n.z * n.x)
        + frameUniforms.iblSH[8] * (n.x * n.x - n.y * n.y)
#endif
        , 0.0);
}
```

Where `n` is the surface normal.

**Comment by romainguy** [comment]
I wonder if the issue could come from here: https://github.com/google/filament/blob/master/tools/cmgen/src/Cubemap.h#L118

I don't know if the direction is supposed to be the direction of the light or the direction to a point on the cubemap. @pixelflinger would know.

**Comment by TimvanScherpenzeel** [comment]
I just [remembered](https://github.com/AnalyticalGraphicsInc/cesium/pull/7172#issuecomment-451118391) that Cesium.js is also using the wrong reconstruction because their current implementation looks like this: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/sphericalHarmonics.glsl and should be using the implementation you mentioned above (as they also generate SH through `cmgen`).

I swapped out the reconstruction in the SH visualizer with the implementation in Filament which now renders correctly. So it looks like there is nothing wrong in Filament but rather in Cesium.js and we can't just 1:1 input the SH generated by `cmgen` in the visualizer tool.

So my issue has been solved, thanks :+1:

<img width="792" alt="screen shot 2019-01-29 at 20 49 42" src="https://user-images.githubusercontent.com/11870513/51935988-81a5ab80-2407-11e9-9e22-a592490e5a8e.png">

**Comment by pixelflinger** [comment]
I'm having trouble tracking which problems are still problems :-)
I'm finally having some cycles to look at cmgen, will do this this week.

**Comment by pixelflinger** [comment]
I can't speak for `Babylon.js` -- I have no idea how they implemented SH reconstruction. But I've run some tests with filament, and generating the SH with `--sh=3` and `--sh-output=file` gives the correct result.  It also works with `--sh-shader`.

`--sh-shader` means "whatever format filament needs", so you can't really use them in another engine. However, in practice, our output seems to match what [ed.ilogues.com](http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization) expects.

`--sh-shader` currently premultiplies by the SH basis and 1/pi, which means that `sh[0]` has the dimension of a color, i.e.: it *is* the average irradiance of the scene. You can use it directly as a linear color in the shader.  You can verify this by running `cmgen` on the `white_furnace.exr` environment, `--sh-shader` will output `SH[0]=1` as expected, and this seems to match [ed.ilogues.com](http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization).

When I use `--sh=3` and I plug that into [ed.ilogues.com](http://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization), I do get the wrong exposure and vertically inverted environment, but that's just because we're not feeding it what it expects.

We need a visualizer that takes *raw* SHs to test this.

I don't think there is a problem with `cmgen`, unless I'm not understanding what's not looking right.


Here is the image I used for my tests:

![debug](https://user-images.githubusercontent.com/1240896/53133876-aa622200-3529-11e9-820f-4bfc56fee4cf.png)


And the result I got with both `--sh=3` and `--sh-shader` using `--no-mirror`:

![3](https://user-images.githubusercontent.com/1240896/53134018-2d837800-352a-11e9-9287-8e1bdfd08f5a.png)
![3s](https://user-images.githubusercontent.com/1240896/53134020-31af9580-352a-11e9-80b7-e4955ce978f9.png)


And this is what the visualizer shows for `--sh-shader --no-mirror`:

<img width="776" alt="3sv" src="https://user-images.githubusercontent.com/1240896/53134190-f3ff3c80-352a-11e9-8ce4-b10ba4b2d547.png">

**Comment by romainguy** [comment]
So it seems that `cmgen` is fine, it's just that we pre-scale the coefficients for runtime efficiency. We could have a "raw" mode that outputs SH without any optimization for compatibility with other tools/engines.

@MiiBond Is that what you're asking for?
