### ISSUE TITLE
render flaw in lastest filament version

### ISSUE THREAD

**Issue by pjinsinan** [google/filament#7444]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I find render flaw with my glb model using lastest filament on desktop， here is contrast：
in filament:
![image](https://github.com/google/filament/assets/5959808/6f934eaf-e4b2-47a3-8785-d88aa57c7538)
![image](https://github.com/google/filament/assets/5959808/1d29aa83-7b3a-4d3d-895e-8d1d723b3840)

in website  https://gltf-viewer.donmccurdy.com/
![image](https://github.com/google/filament/assets/5959808/bac01e7d-4c9c-41d1-9862-464855cc73e8)
![image](https://github.com/google/filament/assets/5959808/e5366e5e-73a8-4127-ae05-a1532bc5c5ab)

I guess whether if some flaw in TBN algorithm, most method show TBN should be calculated in vs or ps， below is my test glb model.
[up.zip](https://github.com/google/filament/files/13722078/up.zip)

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy **full** logs from your console here. Please *do not*
use screenshots of logs, copy them as text, use gist or attach an *uncompressed* file.

**Desktop (please complete the following information):**
 - OS: windows 10
 - GPU: amd
 - Backend: opengl

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

**Comment by bejado** [comment]
The shading errors you're seeing are due to the method Filament's gltfio library uses for tangent computation. By default, we use Langyel's Method to compute tangents whenever UVs, normals, positions, and indices are present in the source model. While Langyel's Method is straightforward to implement, it is less accurate compared to the industry-standard Mikktspace algorithm. In fact, I believe the glTF spec encourages using the [MikkTSpace](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#mikktspace) algorithm.

A workaround for this issue is to import your model into Blender (which uses Mikktspace), then re-export it as a glTF file with tangents included:

![Screenshot 2024-01-03 at 2 59 35 PM](https://github.com/google/filament/assets/5298046/9f6fdccf-cea2-473c-a1fe-8ca130990743)

![Screenshot 2024-01-03 at 3 03 05 PM](https://github.com/google/filament/assets/5298046/df315054-45a9-4f2b-8130-55b80ad99137)

Note that, Filament does provide a `TangentSpaceMesh` class in its geometry library, which implements the Mikktspace algorithm. However, we have not integrated it into gltfio.

**Comment by pjinsinan** [comment]
> The shading errors you're seeing are due to the method Filament's gltfio library uses for tangent computation. By default, we use Langyel's Method to compute tangents whenever UVs, normals, positions, and indices are present in the source model. While Langyel's Method is straightforward to implement, it is less accurate compared to the industry-standard Mikktspace algorithm. In fact, I believe the glTF spec encourages using the [MikkTSpace](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#mikktspace) algorithm.
> 
> A workaround for this issue is to import your model into Blender (which uses Mikktspace), then re-export it as a glTF file with tangents included:
> 
> ![Screenshot 2024-01-03 at 2 59 35 PM](https://private-user-images.githubusercontent.com/5298046/294049623-9f6fdccf-cea2-473c-a1fe-8ca130990743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTk1OTEsIm5iZiI6MTcwNDQxOTI5MSwicGF0aCI6Ii81Mjk4MDQ2LzI5NDA0OTYyMy05ZjZmZGNjZi1jZWEyLTQ3M2MtYTFmZS04Y2ExMzA5OTA3NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDE0ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNmY2E2NjMwNjNlYmQ3NmM1NjhhMDhkM2FiZDM5ODQ2NmMzMzljODFhY2Q2MjViYWY4NjkzYTU0NGQxYmJhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LXic8ZLd-cvEZw1Y48acQgLqF-c2zP3EQSlBRsqH8k4)
> 
> ![Screenshot 2024-01-03 at 3 03 05 PM](https://private-user-images.githubusercontent.com/5298046/294050043-df315054-45a9-4f2b-8130-55b80ad99137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTk1OTEsIm5iZiI6MTcwNDQxOTI5MSwicGF0aCI6Ii81Mjk4MDQ2LzI5NDA1MDA0My1kZjMxNTA1NC00NWE5LTRmMmItODEzMC01NWI4MGFkOTkxMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDE0ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRmZDljOGNjOTJiN2U1ZjNhYzc5NDQyMDBjYWY0OTkyOGMyZmJlZTFhMTc3NmFiODk2MjdiYTRlYTA4ODU1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-y51ssE16J3HIs0imDT01UhPOPZ01BJEk7aBHUDob1c)
> 
> Note that, Filament does provide a `TangentSpaceMesh` class in its geometry library, which implements the Mikktspace algorithm. However, we have not integrated it into gltfio.

thanks a lot， I will try your advice
