### ISSUE TITLE
Translucent objects are not rendered consistently (was: Model rendering issue)

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7500]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
The same model displays different content each time it's loaded.

**To Reproduce**
1. run samples.sample-gltf-viewer
2. Open the app, exit the app, then open the app again. Repeat this process.

**Expected behavior**
The display content should be consistent each time, showing six small spheres.

**Screenshots**

[video](https://github.com/google/filament/assets/6195253/27bb74be-01c5-4aba-add0-97cb57285584)

[light.glb.zip](https://github.com/google/filament/files/13962525/light.glb.zip)

**Smartphone :**
 - Device: OnePlus 9 5g
 - OS: Android 13

**Comment by pixelflinger** [comment]
More precisely, the problem comes from the box -- it is a transparent object that has other transparent objects inside its bounding box. We can't handle that case correctly. You have two ways to fix it:
1. make the box opaque (since it is opaque)
2. set a blend order on the box so that it's always drawn before the balls
