### ISSUE TITLE
Sometimes the light spot from a point light on the ground does not appear

### ISSUE THREAD

**Issue by wddl** [google/filament#7538]
**Describe the bug**
The light spot from the point light on the ground does not appear when the camera angle is parallel

**To Reproduce**
1. At the gltf_viewer sample set the "actualSize" is true
2. Load the gltf and observing the light spot from a point light with both vertical and parallel camera perspectives

**Expected behavior**
The light spot is correctly displayed even under a parallel camera perspective

**Screenshots**
When the camera has a vertical perspective，the light spot is correctly displayed：
![image](https://github.com/google/filament/assets/26518625/b2e22a60-e9b5-4568-957b-8be0d4797f44)
When the camera has a parallel perspective，the light spot is not  displayed：
![image](https://github.com/google/filament/assets/26518625/ce2336c4-369c-4a0d-a503-0b394122e144)

**Logs**

**Desktop (please complete the following information):**
 - OS: [win11]
 - GPU: [ NVIDIA GTX 2060]
 - Backend: [OpenGL]

**Smartphone (please complete the following information):**
 - Device: []
 - OS: [Android]

**Additional context**
this is the gltf file:
[hshl1-c.zip](https://github.com/google/filament/files/14110016/hshl1-c.zip)

**Comment by pixelflinger** [comment]
I'm not sure there is a problem here, That's just how specular reflections work. Were you able to try it in another player?

**Comment by wddl** [comment]
> I'm not sure there is a problem here, That's just how specular reflections work. Were you able to try it in another player?

@pixelflinger thanks!
This is the effect in blender, when camera  angle is parallel :
![image](https://github.com/google/filament/assets/26518625/99757559-33ef-4903-8307-6d28b8613565)
but in the filament i found that by increasing the falloff value of the point light to 30 or above (the default value is 10), light spots also appear. So, was the reason it didn't display before because the falloff value was too low?But the distance in Blender is also 10 meters.

**Comment by pixelflinger** [comment]
Okay, that's interesting. I will investigate further. It might take a few days.

**Comment by pixelflinger** [comment]
So I did some investigation and in fact this is the expected behavior, but it is *very counter intuitive*.

The light "falloff" is not a real property of lights, we do it because we need to limit the influence of lights with the distance for performance reasons, the "falloff" is not a physical property. So the fallof essentially "cuts" the light at certain distance (in your case 10 meters).

Okay given that, when you put the camera closer to the ground, the reflection of the light on the ground moves *away* from the light (towards the camera), and if it falls beyond the falloff (i.e. radius), it won't reflect. Unlike what you might think, the reflected ray doesn't come from "just bellow" the light.

You can increase the radius but it will impact performance significantly on a scene like that.

I do not know why blender behaves differently, but we don't aim to be compatible with blender. I have no idea how they use the falloff / radius.

![PXL_20240201_062437208 RAW-01 COVER~2](https://github.com/google/filament/assets/1240896/ff062a40-5f56-4de1-b535-6f807b553c76)

**Comment by romainguy** [comment]
In Blender the falloff is non physically based and controls the actual falloff (between quadratic and linear). In Filament it's more like a hard clip distance.

**Comment by wddl** [comment]
@pixelflinger @romainguy Thank you very much! I understand this issue. Thank you all for your work！
