### ISSUE TITLE
The combination of internal format=31 and {format=6, type=6} is not supported

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#7549]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I am using the loadTexture method in the TextureLoader class to load textures，But the program crashed.

**To Reproduce**
1. Using images with a resolution of 2048*2048, 64-bit with transparency channels causes the program to crash

**Expected behavior**
Able to correctly load textures.

**Logs**
```
Panicn setImage:255
 reason: The combination of internal format=31 and {format=6, type=6} is not supported.
```

**Comment by romainguy** [comment]
Please share the texture.

**Comment by romainguy** [comment]
You are using a 16 bit, 4 channel PNG, and there's no format in GLES that's suitable for this (with filtering) except for GL_RGBA16F. GL_RGBA16F requires a conversion though as it's not a normalized format like PNG 16 bit, and that's why you are seeing this error. You need to perform that conversion and use the texture APIs directly instead of using the loadTexture() helper. I would also not recommend using this format because of memory and performance impact.
