### ISSUE TITLE
Remove thread id assertion

### ISSUE THREAD

**Issue by vincentdchan** [google/filament#7560]
**Is your feature request related to a problem? Please describe.**
Since #7544 is closed, I still have a problem.

Filament has no plan to support thread-safe API, I am going to wrap Filament in a mutex.
But Filament assert the thread id, which make it impossible to be used in multi-thread env.

`filament/backend/include/private/backend/CommandStream.h`

```cpp
inline void* allocateCommand(size_t size) {
    assert_invariant(utils::ThreadUtils::isThisThread(mThreadId));
    return mCurrentBuffer.allocate(size);
}
```

**Describe the solution you'd like**
Can we remove this assertion? Or provide a flag to disable it.

**Describe alternatives you've considered**
No

**OS and backend**
MacOS/iOS

**Comment by poweifeng** [comment]
Filament's API was designed to run on a single thread.  Instead using mutex on Filament, maybe you could submitting API calls to a thread queue and then run Filament on that thread.  Obviously there's going to be performance consideration depending on how you implement it.

**Comment by pixelflinger** [comment]
Could you give some examples of what APIs you'd like to call from different threads? Is it for performance or convenience?

**Comment by pixelflinger** [comment]
@vincentdchan I think your use case will work (if we remove the thread-id check). 
Because of implementation details in our thread-pool, it wouldn't work to call `Renderer::render()` from different threads for instance.

There are a few things you need to be aware of though:

- You indeed need a lock around *all* filament calls, mostly because we have a single CommandBuffer which any API may use and it's not thread safe.
- BeginFrame/EndFrame will call your callbacks (e.g. all Pixel/BufferDescriptor), so that means callbacks are
  - always called on the "main thread"
  - and will be called with your lock held, which is a recipe for disaster (meaning deadlocks)
  - one way to improve this is to *always* use a `CallbackHandler` when specifying callbacks and use your OS's facilities to post them into the thread you want.
  

I would suggest you comment that code for now and try and let us know how it goes.

**Comment by vincentdchan** [comment]
Thank you for clarifying. I've removed that line of code and have been running my app for a while. Until now, everything works fine.

1. The rendering thread: I call all the render(view)/beginFrame/endFrame functions.
2. The scripting thread: add/remove/move objects. <-- I can post a message to the main thread to create an object asynchronously, but I think it's weird and bad for performance.

I can simply remove this line of the code in my project as a workaround. In the long run, I hope Filament can provide more thread-friendly APIs because Filament's rendering effects are pretty good.

**Comment by pixelflinger** [comment]
The problem with your multi threaded approach is that even if we try really hard to not block the main thread in render(), this is where we're using a more substantial amount of cpu. Depending on your scene, this could block for a few ms. This means that your scripting thread could also block because of the mutex.

If you used messages, this wouldn't happen, instead the actual object creation could be delayed a bit, but that would happen even with the mt solution.

The key here is that almost all filament APIs return immediately, except render(). So queuing that work to the main thread is not going to be a huge hit, but it'll avoid to "lock" your scripting thread execution to the rendering thread.

**Comment by vincentdchan** [comment]
I got it. Actually for my case "blocking" the script thread for a few seconds is acceptable because I want to make the API "sync". Using the messages will require some extra works to sync states between threads.

Also I think it would be a little wired to wrap all the operations of filament to messages(creation/transforming/scaling). It's not convenient. But if it's the recommended way, I will have a try. Thanks!
