### ISSUE TITLE
Android Transparent background rendering always drawn in front of other views

### ISSUE THREAD

**Issue by danybony** [google/filament#7795]
**Describe the bug**
When setting the scene like in the Android transparent rendering sample (without skybox, not opaque) the render is always drawn on top of all other Android views, even if they should be on top according to the hierarchy.  

**To Reproduce**
In https://github.com/google/filament/blob/main/android/samples/sample-transparent-view/src/main/java/com/google/android/filament/transparentrendering/MainActivity.kt#L111-L116 invert the two `addView()` invocations so that the `surfaceView` is added to the `FrameLayout` _before_ the `TextView`.

**Expected behavior**
The text should be displayed in front of the rendered triangle

**Screenshots**
The text is instead always drawn below, like in the original sample
![Screenshot_20240424_131841](https://github.com/google/filament/assets/3942812/3376a1e2-42cb-4ae8-8419-dbde81dd8cf9)

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: Android API 33

**Comment by romainguy** [comment]
That's not how SurfaceView work. A SurfaceView can't be "sandwiched" between Views as it cuts a hole through the window. The content of the SurfaceView is either above your activity, or below. This can be controlled with the zorder on the SurfaceView. Filament's UI utilities automatically set the zorder to be "on top" for transparent rendering because it's what makes the most sense. If you want your Filament rendering sandwiched between Views, use TextureView instead.
