### ISSUE TITLE
Documentation for point and line rendering

### ISSUE THREAD

**Issue by rawnsley** [google/filament#793]
The **PrimitiveType** enum includes POINTS and LINES, which are accepted by the RenderableManager.Builder and do render with default values. However, I can't see anyway to influence things like gl_PointSize or to add an intermediate shader that turns triangles into lines for wireframe.

The main driver for this is that I want to render incomplete geometry during the loading process. For instance, use wireframe triangle meshes while I wait for their bitmap textures to load. Alternative suggestions are also welcome.

**Comment by prideout** [comment]
Regarding an intermediate shader that turns triangles into lines: geometry shaders and `glPolygonMode` are not supported (because Filament is mobile friendly) so you would need to do this yourself on the CPU side.

Regarding point sprites, this is untested but in your mat file I think you can simply do:

```
vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        gl_PointSize = 16.0;
    }
}
```

**Comment by rawnsley** [comment]
This is perfect - thank you!
