### ISSUE TITLE
Cropped viewport in samples with Vulkan

### ISSUE THREAD

**Issue by cleak** [google/filament#801]
**Describe the bug**
When running samples such as `lightbulb` and `material_sandbox` with a Vulkan backend, the viewport appears incorrect with strange borders on the top and right. The same samples with an OpenGL backend don't have the problem. See the attached screenshots of `material_sandbox` comparing OpenGL and Vulkan.

**To Reproduce**
Run `material_sandbox` with IBL and Vulkan like:
```
samples/material_sandbox.exe --api vulkan --ibl=samples/envs/pillars assets/models/monkey/monkey.obj
```

**Expected behavior**
There should be no black bars, just like with OpenGL.

**Screenshots**

With Vulkan:
![ms_vulkan](https://user-images.githubusercontent.com/1058747/52541015-1cc24d80-2d45-11e9-8715-c9a52b386581.png)

With OpenGL:
![ms_opengl](https://user-images.githubusercontent.com/1058747/52541016-1d5ae400-2d45-11e9-9c54-11e18dae63fe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA GTX 1060
 - Backend: Vulkan

**Comment by prideout** [comment]
Thanks, I'll take a look.

**Comment by sven-kr** [comment]
I have the same problem as cleak, also only with Vulkan on Windows 10.
Windows 10 Pro, Version 1809, Build 17763.316. Compiled with CMake/Ninja.
Problem appears in debug and release builds.

I've debugged a bit:
- In FilamentApp.cpp, Line 419, FilamentApp::Window::Window(...), SDL_CreateWindow(..) is called with width = 1024, h=640 and a native Window pointer is stored via: 
void* nativeWindow = ::getNativeWindow(mWindow);  (line 427)
- Later, in PlatformVkWindows.cpp, Line 47+, PlatformVkWindows::createVkSurfaceKHR(...), a Windows device context & Windows handle is constructed via:
HDC deviceContext = (HDC) nativeWindow;
HWND window = WindowFromDC(deviceContext); 
and the new (outer ?) window dimensions are requested via (line 58+):
RECT rect;
BOOL success = GetWindowRect(window, &rect);
and new width/height is calculated from "rect".
This time the resulting width/height is: 1040x679.
That's both wider and higher than 1024x640 above. (+16/+39).
Part of it might account for the title bar (height), but the rest (width) is unclear.
Something does not seems quite right with this code / results.
- Btw., I assume your code takes High DPI calculations & adjustments into account ?

I had to stop further debugging because of time constraints, but maybe this helps a bit 😎 

Cheers & Thanks for the nice filament engine 😃

**Comment by prideout** [comment]
Thanks!  cc @bejado

**Comment by sven-kr** [comment]
OK - here's the fix (had some more time to debug ;)

In file PlatformVKWindows.cpp, Line 59:
( https://github.com/google/filament/blob/master/filament/src/driver/vulkan/PlatformVkWindows.cpp )

BOOL success = GetWindowRect(window, &rect);

has to be replaced by:
BOOL success = GetClientRect(window, &rect);

Now all works without displacement / cropping of the drawing surface with Vulkan.

Background:
GetWindowRect(..) gets the dimensions of the _outer_ Window(incl. Title bar, border etc.)
Also, Windows 10 seems to do strange things with hidden window borders, which you don't see on screen, but which are included in the calculations for the outer window dimensions.

GetClientRect(..) gets the dimension of the inner "client" area, which is what we want here.

High DPI scaling should be OK too (real physical sizes/coordinates returned), because of the 
SDL_CreateWindow(...) with the SDL_WINDOW_ALLOW_HIGHDPI flag set in FilamentApp.cpp.
I tested this a bit with setting different DPI scalings (>100%) and it seemed to work on my monitor (but it's "only" a 2560x1440 screen ;) 

You could also use SDL_VulkanGetDrawableSize(...) to get the client area, however, I am quite sure that
in PlatformVKWindows.cpp you should not have a dependency to SDL in order to also allow using these parts of filament with other frameworks (e.g. glfw, etc.).

I won't do a PR just for this one-liner. Maybe the filament team can just add this to the project with the next change after some more testing ;)

Thanks & Cheers :)

P.S.: There's still another hard crash (existed before the fix), if you try to resize the window with a double 
        click on the window title bar.
        Workaround: use the sizing icon at the top right of the window instead: ⬜️ .

**Comment by bejado** [comment]
@sven-kr Thanks for the investigation! That indeed sounds like the correct fix. I'll verify on my end and put up a PR.
