### ISSUE TITLE
Textures occasionally not displaying problem

### ISSUE THREAD

**Issue by yuxinabc** [google/filament#8017]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
I used textures to implement a model with a grid, but every time I entered the page, the textures were sometimes invisible. I used sample-gltf-viewer for testing.

**To Reproduce**
If you enter the application repeatedly, there is a chance of recurrence.

**Expected behavior**
Every time you enter, the grid should show

**Smartphone (please complete the following information):**
 - Device: oneplus 9r 5g
 - OS: Android 13

**Additional context**

[video](https://github.com/user-attachments/assets/921d5ec0-0d0b-4dc1-8695-aa960470d5f7)
[model](https://github.com/user-attachments/files/16508111/test.zip)

**Comment by pixelflinger** [comment]
It looks like there is sorting problem with the "grid" object. 
My guess is that both objects are "transparents" and this problem would definitely be fixed if the "box" was opaque.

I will argue that the asset is incorrect because it contains a transparent object intersecting another transparent object and currently we can't handle that very well -- there will always be some camera angles that don't work -- like when looking at it from the side.

**Comment by yuxinabc** [comment]
> It looks like there is sorting problem with the "grid" object. My guess is that both objects are "transparents" and this problem would definitely be fixed if the "box" was opaque.
> 
> I will argue that the asset is incorrect because it contains a transparent object intersecting another transparent object and currently we can't handle that very well -- there will always be some camera angles that don't work -- like when looking at it from the side.

Yes, there is a problem with BLEND support. My solution is to customize the material and replace the problematic material.
