### ISSUE TITLE
Support skyboxes and ibl from png/jpg

### ISSUE THREAD

**Issue by richardanaya** [google/filament#879]
Right now there's only support for ktx files.  If its not a huge amount of effort, maybe support png/jpeg too. Sometimes its just way more easy to have one of those files on hand since they don't require a converter. Thank you!

**Comment by romainguy** [comment]
IBLs need to run through our cmgen tool no matter what (which can output KTX). Skyboxes can be generated as KTX by cmgen too. Filament itself doesn't care about the image format, we added KTX as a convenience because all files can be packed in a single one. PNG/JPEG requires many files. Note that our samples do support PNG IBLs and skyboxes already.
